/*
 * test_almanac.cpp - WiPhone/astro.cpp against independent ground truth: tests/vectors_almanac.h,
 * generated by tools/gen_almanac_vectors.py from PyEphem (libastro, the XEphem engine). Every
 * day row's sun and moon events, every sampled sun/moon position and phase, every next quarter
 * and season - plus the calendar helpers, legal light and the solunar rating by hand.
 *
 * A wrong moonrise looks exactly as plausible as a right one; this is the only place that can
 * tell. Never edit the vectors or loosen a tolerance to make this pass - fix astro.cpp.
 *
 * The one allowance (docs/almanac.md, "Events in a local day"): when this code and PyEphem
 * disagree on whether an event HAPPENS in the day, that is accepted only if the day's extreme of
 * the event's function (altitude relative to its threshold) is within 0.1 deg of zero - a
 * grazing pass that either implementation may legitimately find or miss. Those are counted and
 * must stay under 2% of the events.
 */

#include "../WiPhone/astro.h"
#include "vectors_almanac.h"
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>

static int failures = 0;
static int checks = 0;

#define CHECK(cond, name) do { \
    checks++; \
    if (cond) { printf("  ok  %s\n", name); } \
    else { printf("  FAIL %s (line %d)\n", name, __LINE__); failures++; } \
  } while (0)

// Quiet: counts every check, prints only a failure (the vector loops run thousands).
#define CHECKQ(cond, ...) do { \
    checks++; \
    if (!(cond)) { printf("  FAIL "); printf(__VA_ARGS__); printf(" (line %d)\n", __LINE__); failures++; } \
  } while (0)

#define N_OF(a) (sizeof(a) / sizeof((a)[0]))

static double wrap180(double x) {
  double r = fmod(x, 360.0);
  if (r < -180.0) r += 360.0;
  if (r >= 180.0) r -= 360.0;
  return r;
}

// Worst error per quantity.
struct Worst { const char* name; const char* unit; double err; const char* place; long long at; };
static void note(Worst* w, double err, const char* place, long long at) {
  if (err > w->err) { w->err = err; w->place = place; w->at = at; }
}
static void printWorst(const Worst* w, double tol) {
  printf("  worst %-16s %10.4f %-3s (tol %g) %s @ %lld\n", w->name, w->err, w->unit, tol,
         w->place ? w->place : "-", w->at);
}

// ---- the grazing measure --------------------------------------------------------------------

enum { EV_DAWN, EV_RISE, EV_NOON, EV_SET, EV_DUSK, EV_MRISE, EV_MSET, EV_MTRANSIT, EV_MUNDER, EV_N };
static const char* EV_NAME[EV_N] = { "sun dawn", "sunrise", "solar noon", "sunset", "sun dusk",
                                     "moonrise", "moonset", "moon transit", "moon underfoot" };

/* The event's function at t: altitude relative to its threshold (deg), computed with astro.cpp's
 * own public functions. Rise/set: centre alt + 34' + semidiameter; civil: centre alt + 6. */
static double eventFn(int ev, int64_t t, double lat, double lon) {
  double alt, az;
  if (ev == EV_DAWN || ev == EV_DUSK) {
    astroSunPos(t, lat, lon, &alt, &az);
    return alt + 6.0;
  }
  if (ev == EV_RISE || ev == EV_SET) {
    astroSunPos(t, lat, lon, &alt, &az);
    return alt + 0.5667 + astroSunSemidiameter(t);
  }
  astroMoonPos(t, lat, lon, &alt, &az);
  return alt + 0.5667 + astroMoonSemidiameter(t, lat, lon);
}

/* How close the day's extreme came to the threshold: min(|max f|, |min f|) over [t0, t0+86400],
 * sampled every 60 s (a parabola's peak between 60 s samples is off by < 1e-4 deg). The window's
 * ends are part of the day, so an event within seconds of midnight (on either side, depending on
 * who computed it) also lands here - the same ambiguity, and it is printed and counted the same
 * way. Returns a large number for the hour-angle events, which cannot graze. */
static double grazingMargin(int ev, int64_t t0, double lat, double lon) {
  if (ev == EV_NOON || ev == EV_MTRANSIT || ev == EV_MUNDER) return 1e9;
  double lo = 1e9, hi = -1e9;
  for (int64_t t = t0; t <= t0 + 86400; t += 60) {
    double f = eventFn(ev, t, lat, lon);
    if (f < lo) lo = f;
    if (f > hi) hi = f;
  }
  double a = fabs(lo), b = fabs(hi);
  return a < b ? a : b;
}

/* ERRATA - rows where the VECTOR is wrong, each proven with PyEphem itself (not with astro.cpp).
 * PyEphem 4.2's next_rising() judges "never up" by the declination AT THE SEARCH'S START, so from
 * some starts it raises NeverUpError although the body does rise later that day. The first cut of
 * tools/gen_almanac_vectors.py wrote that as "no event"; this table held the one row it broke
 * (utqiagvik t0=1787734800, moonrise 1787814266, found by this test's first build). The generator
 * now retries from each later hour of the window, the row is right, and the table is empty - the
 * mechanism stays for the next reference bug. The check near the end pins the regenerated row. */
struct Erratum { const char* place; int64_t t0; int ev; int64_t want; const char* evidence; };
static const Erratum ERRATA[] = { { "", 0, -1, 0, "" } };   // sentinel only (a C++ array cannot be empty)
static const size_t N_ERRATA = 0;

static const Erratum* erratum(const char* place, int64_t t0, int ev) {
  for (size_t i = 0; i < N_ERRATA; i++) {
    if (ERRATA[i].t0 == t0 && ERRATA[i].ev == ev && strcmp(ERRATA[i].place, place) == 0) return &ERRATA[i];
  }
  return 0;
}

int main() {
  printf("test_almanac\n");

  // ---- unit checks: names, calendar, DST ---------------------------------------------------
  {
    static const char* const want[8] = { "New", "Waxing crescent", "First quarter", "Waxing gibbous",
                                         "Full", "Waning gibbous", "Last quarter", "Waning crescent" };
    bool all = true;
    for (int i = 0; i < 8; i++) all = all && strcmp(astroPhaseName(i), want[i]) == 0;
    CHECK(all, "astroPhaseName 0..7");
    CHECK(strcmp(astroPhaseName(8), "?") == 0 && strcmp(astroPhaseName(-1), "?") == 0,
          "astroPhaseName out of range is ?");
    CHECK(strcmp(astroSolunarRatingName(0), "Poor") == 0 && strcmp(astroSolunarRatingName(4), "Excellent") == 0,
          "astroSolunarRatingName ends");
  }
  {
    int y, m, d, wd, yd;
    astroCivil(0, &y, &m, &d, &wd, &yd);
    CHECK(y == 1970 && m == 1 && d == 1 && wd == 4 && yd == 1, "civil: epoch is Thu 1970-01-01, yday 1");
    astroCivil(-1, &y, &m, &d, &wd, &yd);
    CHECK(y == 1969 && m == 12 && d == 31 && wd == 3 && yd == 365, "civil: one second before the epoch is Wed 1969-12-31");
    astroCivil(1709164800LL, &y, &m, &d, &wd, &yd);                  // 2024-02-29 00:00
    CHECK(y == 2024 && m == 2 && d == 29 && wd == 4 && yd == 60, "civil: leap day 2024-02-29 (Thu, yday 60)");
    astroCivil(1709164800LL + 86400, &y, &m, &d, &wd, &yd);
    CHECK(y == 2024 && m == 3 && d == 1 && yd == 61, "civil: 2024-03-01 follows the leap day");
    astroCivil(951782400LL, &y, &m, &d, &wd, &yd);                   // 2000-02-29 (400-year leap)
    CHECK(y == 2000 && m == 2 && d == 29 && wd == 2, "civil: 2000-02-29 exists (Tue)");
    astroCivil(4107542400LL, &y, &m, &d, &wd, &yd);                  // 2100-03-01 (no Feb 29 in 2100)
    CHECK(y == 2100 && m == 3 && d == 1 && yd == 60, "civil: 2100 is not a leap year");
    astroCivil(1735603200LL, &y, &m, &d, &wd, &yd);                  // 2024-12-31
    CHECK(y == 2024 && m == 12 && d == 31 && yd == 366, "civil: 2024-12-31 is yday 366");
    // Negative-offset midnights: local midnight at UTC-7 and UTC-10 is still that local date.
    int64_t utcMid = 1790812800LL;                                   // 2026-10-01 00:00 UTC
    int64_t t0pdt = utcMid + 7 * 3600;                               // 2026-10-01 00:00 PDT
    astroCivil(t0pdt - 7 * 3600, &y, &m, &d, &wd, &yd);
    CHECK(y == 2026 && m == 10 && d == 1 && wd == 4, "civil: PDT midnight 2026-10-01 is Thursday Oct 1");
    astroCivil(t0pdt - 7 * 3600 - 1, &y, &m, &d, &wd, &yd);
    CHECK(y == 2026 && m == 9 && d == 30 && wd == 3 && yd == 273, "civil: one second earlier is Wed Sep 30 (yday 273)");
    astroCivil(utcMid + 23 * 3600 + 59 * 60 - 10 * 3600, &y, &m, &d, &wd, &yd); // 23:59 UTC at UTC-10
    CHECK(y == 2026 && m == 10 && d == 1, "civil: 23:59 UTC at UTC-10 is still Oct 1 local");
    astroCivil(utcMid + 3600 - 10 * 3600, &y, &m, &d, &wd, &yd);             // 01:00 UTC at UTC-10
    CHECK(y == 2026 && m == 9 && d == 30, "civil: 01:00 UTC at UTC-10 is the previous day, Sep 30");
    // round trip over 4,400 years of days, both sides of the epoch and back past year 0 (the
    // era arithmetic of negative years)
    bool rt = true;
    for (int64_t day = -800000; day <= 800000 && rt; day += 37) {
      astroCivil(day * 86400 + 43200, &y, &m, &d, &wd, &yd);
      rt = astroDaysFromCivil(y, m, d) == day;
    }
    CHECK(rt, "civil: astroDaysFromCivil inverts astroCivil (-800000..800000 days, years -220..4160)");
    CHECK(astroDaysFromCivil(2026, 9, 27) == 20723, "astroDaysFromCivil(2026-09-27) = 20723");
  }
  {
    CHECK(astroIsoWeek(2026, 1, 1) == 1, "ISO week: 2026-01-01 is week 1 of 2026");
    CHECK(astroIsoWeek(2027, 1, 1) == 53, "ISO week: 2027-01-01 is week 53 of 2026");
    CHECK(astroIsoWeek(2029, 12, 31) == 1, "ISO week: 2029-12-31 is week 1 of 2030");
    CHECK(astroIsoWeek(2026, 12, 31) == 53, "ISO week: 2026-12-31 is week 53");
    CHECK(astroIsoWeek(2026, 9, 27) == 39, "ISO week: 2026-09-27 (a Sunday) is week 39");
    CHECK(astroIsoWeek(2021, 1, 3) == 53, "ISO week: 2021-01-03 is week 53 of 2020");
    CHECK(astroIsoWeek(2021, 1, 4) == 1, "ISO week: 2021-01-04 is week 1 of 2021");
  }
  {
    int mar = 0, nov = 0;
    astroUsDst(2026, &mar, &nov);
    CHECK(mar == 8 && nov == 1, "US DST 2026: Mar 8 / Nov 1");
    astroUsDst(2027, &mar, &nov);
    CHECK(mar == 14 && nov == 7, "US DST 2027: Mar 14 / Nov 7");
    astroUsDst(2025, &mar, &nov);
    CHECK(mar == 9 && nov == 2, "US DST 2025: Mar 9 / Nov 2");
  }

  // ---- the theories against published worked examples --------------------------------------
  {
    CHECK(astroJd(0) == 2440587.5 && astroJd(946728000LL) == 2451545.0, "astroJd: epoch and J2000.0");
    // Meeus, Astronomical Algorithms, example 47.a: 1992 April 12, 0h TD -> the geometric
    // lambda 133.162655, beta -3.229126, distance 368409.7 km - the big rows of tables 47.A/B.
    // (The small rows were checked once, 2026-09-27: a least-squares fit of astro.cpp's residuals
    // against PyEphem's geocentric moon at 3000 instants put no row off by more than 0.5".)
    double lon = 0, lat = 0, km = 0;
    astroMoonEcliptic(703036800LL - (int64_t)astroDeltaT(), &lon, &lat, &km);
    CHECK(fabs(lon - 133.162655) < 2e-6 && fabs(lat - -3.229126) < 2e-6 && fabs(km - 368409.7) < 0.1,
          "moon: Meeus example 47.a (1992-04-12 0h TD) lambda/beta/distance");
    CHECK(fabs(astroMoonDistanceKm(703036800LL - (int64_t)astroDeltaT()) - 368409.7) < 0.1,
          "moon: astroMoonDistanceKm agrees with the ecliptic place");
    // The example passes UT = TD - astroDeltaT(), so it cannot see a wrong constant (DELTA_T = 0
    // passed every check here - review 2026-09-27). TT - UT was 69.1-69.3 s through 2020-2026; the
    // end-to-end guard is the phase bias against PyEphem below.
    CHECK(astroDeltaT() >= 66.0 && astroDeltaT() <= 75.0, "TT - UT is the 2020s value (~69 s)");
    // semidiameters in their physical ranges
    double sdS = astroSunSemidiameter(1767225600LL), sdS2 = astroSunSemidiameter(1782864000LL);
    CHECK(sdS > 0.2705 && sdS < 0.2720 && sdS2 > 0.2615 && sdS2 < 0.2630,
          "sun semidiameter: ~16.3' at perihelion (Jan), ~15.8' at aphelion (Jul)");
    double sdM = astroMoonSemidiameter(703036800LL, 47.5, -121.8);
    CHECK(sdM > 0.24 && sdM < 0.29, "moon semidiameter in 0.24..0.29 deg");
  }

  // ---- robustness: the poles, the date line, a night that never ends -------------------------
  {
    const double LATS[] = { 90.0, 89.99, -90.0, -89.99, 0.0 };
    const double LONS[] = { 180.0, -180.0, 0.0 };
    bool sane = true;
    for (size_t i = 0; i < N_OF(LATS); i++) {
      for (size_t j = 0; j < N_OF(LONS); j++) {
        for (int64_t t0 = 1767225600LL; t0 < 1798761600LL; t0 += 86400 * 29) {
          AstroSunDay s;
          AstroMoonDay mo;
          astroSunDay(t0, LATS[i], LONS[j], &s);
          astroMoonDay(t0, LATS[i], LONS[j], &mo);
          int64_t all[9] = { s.dawn, s.rise, s.noon, s.set, s.dusk, mo.rise, mo.set, mo.transit, mo.under };
          for (int k = 0; k < 9; k++) {
            if (all[k] != 0 && (all[k] < t0 || all[k] >= t0 + 86400)) sane = false;
          }
          double alt, az;
          astroMoonPos(t0, LATS[i], LONS[j], &alt, &az);
          if (!(alt >= -90.0 && alt <= 90.0 && az >= 0.0 && az < 360.0)) sane = false;
          astroSunPos(t0, LATS[i], LONS[j], &alt, &az);
          if (!(alt >= -90.0 && alt <= 90.0 && az >= 0.0 && az < 360.0)) sane = false;
        }
      }
    }
    CHECK(sane, "poles and date line: every event inside its day, every position finite and in range");
    AstroSunDay s;
    astroSunDay(1781740800LL + 9 * 3600, 71.2906, -156.7886, &s);   // Utqiagvik (UTC-9), 2026-06-18
    CHECK(s.rise == 0 && s.set == 0 && s.dawn == 0 && s.dusk == 0 && s.noon != 0,
          "midnight sun: no rise/set/twilight, noon still happens");
    astroSunDay(1797552000LL + 9 * 3600, 71.2906, -156.7886, &s);   // Utqiagvik (UTC-9), 2026-12-18
    CHECK(s.rise == 0 && s.set == 0 && s.dawn != 0 && s.dusk != 0 && s.noon != 0,
          "polar night: no sunrise, but civil twilight at noon");

    // The antimeridian: 180 E and 180 W are one place.
    bool same = true;
    for (int64_t t0 = 1767225600LL + 12 * 3600; t0 < 1798761600LL; t0 += 86400 * 13) {
      AstroSunDay a, b;
      AstroMoonDay ma, mb;
      astroSunDay(t0, -16.5, 180.0, &a);
      astroSunDay(t0, -16.5, -180.0, &b);
      astroMoonDay(t0, -16.5, 180.0, &ma);
      astroMoonDay(t0, -16.5, -180.0, &mb);
      int64_t x[9] = { a.dawn, a.rise, a.noon, a.set, a.dusk, ma.rise, ma.set, ma.transit, ma.under };
      int64_t y[9] = { b.dawn, b.rise, b.noon, b.set, b.dusk, mb.rise, mb.set, mb.transit, mb.under };
      for (int k = 0; k < 9; k++) {
        if ((x[k] == 0) != (y[k] == 0) || llabs((long long)(x[k] - y[k])) > 1) same = false;
      }
      double a1, z1, a2, z2;
      astroMoonPos(t0, -16.5, 180.0, &a1, &z1);
      astroMoonPos(t0, -16.5, -180.0, &a2, &z2);
      if (fabs(a1 - a2) > 1e-9 || fabs(wrap180(z1 - z2)) > 1e-9) same = false;
    }
    CHECK(same, "antimeridian: lon 180 and -180 give the same events and moon position");

    // NaN in, no hang and no invented event: every scan and bisection is bounded. (Solar noon
    // does not depend on the latitude, so a NaN latitude still has one.)
    AstroSunDay ns;
    AstroMoonDay nm;
    astroSunDay(1790838000LL, NAN, -121.7868, &ns);
    bool nanOk = !ns.dawn && !ns.rise && ns.noon && !ns.set && !ns.dusk;
    astroSunDay(1790838000LL, 47.4957, NAN, &ns);
    nanOk = nanOk && !ns.dawn && !ns.rise && !ns.noon && !ns.set && !ns.dusk;
    astroMoonDay(1790838000LL, NAN, -121.7868, &nm);
    nanOk = nanOk && !nm.rise && !nm.set && !nm.transit && !nm.under;
    astroMoonDay(1790838000LL, 47.4957, NAN, &nm);
    nanOk = nanOk && !nm.rise && !nm.set && !nm.transit && !nm.under;
    CHECK(nanOk, "NaN latitude / longitude: the day scans return, with no event that needs the NaN");
  }

  // ---- the day's edges: an event whose instant is t0 is that day's; one at t0 + 86400 is not ----
  {
    // Every event of 40 days at North Bend and Fairbanks, asked for again from the day that STARTS
    // at its own instant (it must be that day's first of its kind, to the second) and from the day
    // that ENDS there (it must not be in it). Review 2026-09-27: the first case lost the event from
    // both days (found from its own instant: 2 of 532); `t <= end` would put it in both.
    // Each t0 interpolates the theory through its own 3-h nodes (astro.cpp, "events in a local
    // day"), so a crossing within a hair of a whole second can land one second either side when
    // asked from another t0: found from its own instant 683 of 688, and a meridian passage at a
    // day's last second 151 of 154 (2026-09-27); >= 95% required.
    // Kept out of the day ending there has no such allowance: that must hold for every event.
    const double PL[2][2] = { { 47.4957, -121.7868 }, { 64.8378, -147.7164 } };
    int n = 0, fromOk = 0, endOk = 0, lastSecOk = 0, lastSecN = 0;
    for (int p = 0; p < 2; p++) {
      for (int day = 0; day < 40; day++) {
        int64_t t0 = 1790838000LL + (int64_t)day * 86400;
        AstroSunDay s;
        AstroMoonDay m;
        astroSunDay(t0, PL[p][0], PL[p][1], &s);
        astroMoonDay(t0, PL[p][0], PL[p][1], &m);
        int64_t ev[9] = { s.dawn, s.rise, s.noon, s.set, s.dusk, m.rise, m.set, m.transit, m.under };
        for (int k = 0; k < 9; k++) {
          if (!ev[k]) continue;
          n++;
          int64_t R = ev[k];
          AstroSunDay s2;
          AstroMoonDay m2;
          astroSunDay(R, PL[p][0], PL[p][1], &s2);
          astroMoonDay(R, PL[p][0], PL[p][1], &m2);
          int64_t from[9] = { s2.dawn, s2.rise, s2.noon, s2.set, s2.dusk, m2.rise, m2.set, m2.transit, m2.under };
          if (from[k] == R) fromOk++;
          astroSunDay(R - 86400, PL[p][0], PL[p][1], &s2);
          astroMoonDay(R - 86400, PL[p][0], PL[p][1], &m2);
          int64_t to[9] = { s2.dawn, s2.rise, s2.noon, s2.set, s2.dusk, m2.rise, m2.set, m2.transit, m2.under };
          if (to[k] < R) endOk++;
          else printf("  FAIL the day ending at %lld holds %s at %lld\n", (long long)R, EV_NAME[k], (long long)to[k]);
          // The moon's meridian passages are 24 h 38 min or more apart anywhere, so the day
          // [R - 86399, R + 1) holds this one as its only one of that kind, at its last second.
          // (Its rises and sets are not: at Fairbanks two moonsets can be 23.7 h apart.)
          if (k == EV_MTRANSIT || k == EV_MUNDER) {
            lastSecN++;
            astroMoonDay(R - 86399, PL[p][0], PL[p][1], &m2);
            if ((k == EV_MTRANSIT ? m2.transit : m2.under) == R) lastSecOk++;
          }
        }
      }
    }
    checks += 3;
    bool okFrom = fromOk * 20 >= n * 19, okLast = lastSecOk * 20 >= lastSecN * 19;
    failures += !okFrom + (endOk != n) + !okLast;
    printf("  %s day edges: %d of %d events found from their own instant, %d of %d kept out of the day ending there, "
           "%d of %d meridian passages found at a day's last second\n", okFrom && endOk == n && okLast ? "ok " : "FAIL",
           fromOk, n, endOk, n, lastSecOk, lastSecN);
  }

  // ---- legal light ---------------------------------------------------------------------------
  {
    AstroSunDay s = { 1000000, 1002000, 1020000, 1040000, 1042100 };
    int64_t f = -1, l = -1;
    astroLegalLight(&s, ASTRO_LEGAL_30MIN, &f, &l);
    CHECK(f == 1002000 - 1800 && l == 1040000 + 1800, "legal light 30 min: rise-30 / set+30");
    astroLegalLight(&s, ASTRO_LEGAL_CIVIL, &f, &l);
    CHECK(f == 1000000 && l == 1042100, "legal light civil: dawn / dusk");
    AstroSunDay p = { 1000000, 0, 1020000, 1040000, 0 };
    astroLegalLight(&p, 0, &f, &l);
    CHECK(f == 0 && l == 1040000 + 1800, "legal light 30 min: no sunrise -> no first light");
    astroLegalLight(&p, 1, &f, &l);
    CHECK(f == 1000000 && l == 0, "legal light civil: no dusk -> no last light");
  }

  // ---- the day vectors ---------------------------------------------------------------------
  Worst wEv[EV_N];
  for (int i = 0; i < EV_N; i++) { wEv[i].name = EV_NAME[i]; wEv[i].unit = "s"; wEv[i].err = 0; wEv[i].place = 0; wEv[i].at = 0; }
  int events = 0, grazing = 0, bothAbsent = 0, errataUsed = 0;
  double worstGraze = 0;
  for (size_t r = 0; r < N_OF(ALM_DAYS); r++) {
    const AlmDayVec& v = ALM_DAYS[r];
    AstroSunDay s;
    AstroMoonDay mo;
    astroSunDay(v.t0, v.lat, v.lon, &s);
    astroMoonDay(v.t0, v.lat, v.lon, &mo);
    int64_t want[EV_N] = { v.dawn, v.rise, v.noon, v.set, v.dusk, v.mrise, v.mset, v.mtransit, v.munder };
    int64_t got[EV_N] = { s.dawn, s.rise, s.noon, s.set, s.dusk, mo.rise, mo.set, mo.transit, mo.under };
    for (int e = 0; e < EV_N; e++) {
      int64_t tol = e < EV_MRISE ? 60 : 120;
      const Erratum* er = erratum(v.place, v.t0, e);
      if (er) {
        errataUsed++;
        printf("  note erratum %s %s t0=%lld: vector %lld, PyEphem's own answer %lld (%s)\n", v.place,
               EV_NAME[e], (long long)v.t0, (long long)want[e], (long long)er->want, er->evidence);
        want[e] = er->want;
      }
      if (!want[e] && !got[e]) { bothAbsent++; continue; }
      events++;
      if (want[e] && got[e]) {
        double err = fabs((double)(got[e] - want[e]));
        note(&wEv[e], err, v.place, (long long)v.t0);
        CHECKQ(err <= tol, "%s %s t0=%lld: got %lld want %lld (%+lld s)", v.place, EV_NAME[e],
               (long long)v.t0, (long long)got[e], (long long)want[e], (long long)(got[e] - want[e]));
        continue;
      }
      double margin = grazingMargin(e, v.t0, v.lat, v.lon);
      bool ok = margin <= 0.1;
      if (ok) {
        grazing++;
        if (margin > worstGraze) worstGraze = margin;
        printf("  note grazing %s %s t0=%lld: got %lld want %lld, day extreme %.4f deg from the threshold\n",
               v.place, EV_NAME[e], (long long)v.t0, (long long)got[e], (long long)want[e], margin);
      }
      checks++;
      if (!ok) {
        printf("  FAIL %s %s t0=%lld: presence differs (got %lld want %lld), day extreme %.4f deg from the threshold\n",
               v.place, EV_NAME[e], (long long)v.t0, (long long)got[e], (long long)want[e], margin);
        failures++;
      }
    }
  }
  printf("  day rows %zu: %d events compared, %d both absent, %d grazing allowances (worst %.4f deg)\n",
         N_OF(ALM_DAYS), events, bothAbsent, grazing, worstGraze);

  // The instant is the first whole second at or past the crossing - the definition that makes
  // prev/next exact inverses and the phone and COVEY agree to the second. The vectors (60/120 s)
  // cannot see a 1 s slip (a bisection returning its near end passed them all), so each event of
  // the northern rows (47-71 N) is checked against the event's function evaluated DIRECTLY
  // through the public API: on the near side one second before, on the far side at the instant.
  // The day scan interpolates the theory (astro.cpp), which may move a crossing that lies within
  // a hair of a whole second across it: allowed within 1 s, and for at most 5% of events
  // (measured 2026-09-27: 4273 of 4296 exact with the polar days below, none beyond 1 s).
  // North of 29 N the sun and moon cross the meridian in the south (azimuth 180) and pass
  // underfoot in the north (0).
  {
    int n = 0, exact = 0, within1 = 0;
    for (size_t r = 0; r < N_OF(ALM_DAYS); r++) {
      const AlmDayVec& v = ALM_DAYS[r];
      if (!(v.lat > 40.0)) continue;
      AstroSunDay s;
      AstroMoonDay mo;
      astroSunDay(v.t0, v.lat, v.lon, &s);
      astroMoonDay(v.t0, v.lat, v.lon, &mo);
      int64_t got[EV_N] = { s.dawn, s.rise, s.noon, s.set, s.dusk, mo.rise, mo.set, mo.transit, mo.under };
      static const int DIR[EV_N] = { +1, +1, +1, -1, -1, +1, -1, +1, +1 };
      for (int e = 0; e < EV_N; e++) {
        if (!got[e]) continue;
        bool far[4];   // at instant - 2 .. instant + 1: past the crossing?
        for (int j = 0; j < 4; j++) {
          int64_t t = got[e] - 2 + j;
          double alt, az, f;
          if (e == EV_NOON) {
            astroSunPos(t, v.lat, v.lon, &alt, &az);
            f = az - 180.0;
          } else if (e == EV_MTRANSIT || e == EV_MUNDER) {
            astroMoonPos(t, v.lat, v.lon, &alt, &az);
            f = e == EV_MTRANSIT ? az - 180.0 : (az < 180.0 ? az : az - 360.0);
          } else {
            f = eventFn(e, t, v.lat, v.lon);
          }
          far[j] = DIR[e] > 0 ? f >= 0.0 : f < 0.0;
        }
        n++;
        if (!far[1] && far[2]) { exact++; within1++; }
        else if ((!far[0] && far[1]) || (!far[2] && far[3])) within1++;
        else printf("  FAIL %s %s t0=%lld: instant %lld is not within 1 s of the crossing\n", v.place, EV_NAME[e],
                    (long long)v.t0, (long long)got[e]);
      }
    }
    // Where the sun's altitude crawls, a slightly wrong threshold moves an event by seconds: the
    // sun's rises, sets and twilights near the poles, every day of 2026-2027 (no vectors needed -
    // the reference is the direct evaluation). The semidiameter held at its noon value put 9 of
    // these more than 1 s off, up to 10 s (review 2026-09-27).
    static const double POLAR[3][2] = { { 89.9, 45.0 }, { -89.9, -120.0 }, { -78.0, 166.7 } };
    for (int p = 0; p < 3; p++) {
      for (int day = 0; day < 730; day++) {
        int64_t t0 = 1767225600LL + (int64_t)day * 86400;
        AstroSunDay s;
        astroSunDay(t0, POLAR[p][0], POLAR[p][1], &s);
        int64_t got[5] = { s.dawn, s.rise, 0, s.set, s.dusk };
        for (int e = 0; e < 5; e++) {
          if (!got[e]) continue;
          bool far[4];
          for (int j = 0; j < 4; j++) {
            double f = eventFn(e, got[e] - 2 + j, POLAR[p][0], POLAR[p][1]);
            far[j] = e < EV_SET ? f >= 0.0 : f < 0.0;
          }
          n++;
          if (!far[1] && far[2]) { exact++; within1++; }
          else if ((!far[0] && far[1]) || (!far[2] && far[3])) within1++;
          else printf("  FAIL lat %.1f %s t0=%lld: instant %lld is not within 1 s of the crossing\n", POLAR[p][0],
                      EV_NAME[e], (long long)t0, (long long)got[e]);
        }
      }
    }
    checks += 2;
    failures += (within1 != n) + (exact * 20 < n * 19);
    printf("  %s instants: %d of %d events exactly the first second past the directly evaluated crossing, %d within 1 s\n",
           within1 == n && exact * 20 >= n * 19 ? "ok " : "FAIL", exact, n, within1);
  }
  CHECK(grazing * 50 <= events, "grazing allowances <= 2% of events");
  CHECK(errataUsed == (int)N_ERRATA, "every erratum matched its vector row");
  {
    /* The generator's retry, pinned: this row was "no moonrise" before first_in() learned to
     * retry a NeverUpError from later starts (PyEphem's own answer from t0+75863). */
    bool found = false;
    for (size_t i = 0; i < N_OF(ALM_DAYS); i++) {
      const AlmDayVec& v = ALM_DAYS[i];
      if (strcmp(v.place, "utqiagvik") == 0 && v.t0 == 1787734800LL) {
        found = (v.mrise == 1787814266LL);
      }
    }
    CHECK(found, "the regenerated vectors carry Utqiagvik's 2026-08-26 moonrise (generator retry)");
  }

  // ---- sampled positions and phases ----------------------------------------------------------
  Worst wMoonAlt = { "moon alt", "deg", 0, 0, 0 }, wMoonAz = { "moon az", "deg", 0, 0, 0 };
  Worst wSunAlt = { "sun alt", "deg", 0, 0, 0 }, wSunAz = { "sun az", "deg", 0, 0, 0 };
  Worst wIllum = { "illum", "", 0, 0, 0 }, wSep = { "sep (elong)", "deg", 0, 0, 0 };
  Worst wAge = { "age vs elong", "d", 0, 0, 0 };
  for (size_t r = 0; r < N_OF(ALM_NOWS); r++) {
    const AlmNowVec& v = ALM_NOWS[r];
    double malt, maz, salt, saz;
    astroMoonPos(v.t, v.lat, v.lon, &malt, &maz);
    astroSunPos(v.t, v.lat, v.lon, &salt, &saz);
    AstroMoonPhase ph;
    astroMoonPhaseAt(v.t, &ph);
    double e;
    e = fabs(malt - v.moonAlt); note(&wMoonAlt, e, v.place, (long long)v.t);
    CHECKQ(e <= 0.1, "%s t=%lld moon alt %.4f want %.4f", v.place, (long long)v.t, malt, v.moonAlt);
    if (v.moonAlt < 85.0) {
      e = fabs(wrap180(maz - v.moonAz)); note(&wMoonAz, e, v.place, (long long)v.t);
      CHECKQ(e <= 0.2, "%s t=%lld moon az %.4f want %.4f", v.place, (long long)v.t, maz, v.moonAz);
    }
    e = fabs(salt - v.sunAlt); note(&wSunAlt, e, v.place, (long long)v.t);
    CHECKQ(e <= 0.05, "%s t=%lld sun alt %.4f want %.4f", v.place, (long long)v.t, salt, v.sunAlt);
    e = fabs(wrap180(saz - v.sunAz)); note(&wSunAz, e, v.place, (long long)v.t);
    CHECKQ(e <= 0.05, "%s t=%lld sun az %.4f want %.4f (sun alt %.2f)", v.place, (long long)v.t, saz, v.sunAz, v.sunAlt);
    e = fabs(ph.illum - v.illum); note(&wIllum, e, v.place, (long long)v.t);
    CHECKQ(e <= 0.005, "%s t=%lld illum %.5f want %.5f", v.place, (long long)v.t, ph.illum, v.illum);
    e = fabs(ph.sep - v.elong); note(&wSep, e, v.place, (long long)v.t);
    CHECKQ(e <= 0.1, "%s t=%lld sep %.4f want %.4f", v.place, (long long)v.t, ph.sep, v.elong);
    // the name, the sign and the age agree with the elongation they came from: the spec's bands,
    // waxing = east of the sun, and the age within 1.5 days of elongation / mean synodic motion
    // (the true elongation runs up to ~16 deg off the mean one between two new moons)
    double E = ph.elong;
    int band = (E < 12 || E >= 348) ? 0 : E < 78 ? 1 : E < 102 ? 2 : E < 168 ? 3 : E < 192 ? 4
             : E < 258 ? 5 : E < 282 ? 6 : 7;
    double ageEst = E / (360.0 / 29.530589);
    note(&wAge, fabs(ph.ageDays - ageEst), v.place, (long long)v.t);
    CHECKQ(ph.phase == band && (ph.sep > 0) == (E < 180.0) && fabs(ph.ageDays - ageEst) < 1.5,
           "%s t=%lld elong %.3f: phase %d (band %d) sep %.3f age %.3f (est %.3f)", v.place,
           (long long)v.t, E, ph.phase, band, ph.sep, ph.ageDays, ageEst);
  }
  printf("  now rows %zu checked\n", N_OF(ALM_NOWS));

  // ---- next quarters and seasons ------------------------------------------------------------
  static const char* const Q_NAME[4] = { "new", "first quarter", "full", "last quarter" };
  Worst wPhase = { "moon phases", "s", 0, 0, 0 }, wSeason = { "seasons", "s", 0, 0, 0 };
  bool roundTrip = true;
  double phaseBias = 0.0;
  for (size_t r = 0; r < N_OF(ALM_PHASES); r++) {
    const AlmPhaseVec& v = ALM_PHASES[r];
    for (int q = 0; q < 4; q++) {
      int64_t t = astroNextMoonPhase(v.from, q);
      double e = fabs((double)(t - v.next[q]));
      phaseBias += (double)(t - v.next[q]);
      note(&wPhase, e, Q_NAME[q], (long long)v.from);
      CHECKQ(e <= 300, "next %s from %lld: got %lld want %lld (%+lld s)", Q_NAME[q], (long long)v.from,
             (long long)t, (long long)v.next[q], (long long)(t - v.next[q]));
      int64_t back = astroPrevMoonPhase(t, q);
      if (llabs((long long)(back - t)) > 1) {
        roundTrip = false;
        printf("  FAIL prev(next(%lld, %d)) = %lld, not %lld\n", (long long)v.from, q, (long long)back, (long long)t);
      }
      // previous strictly before the next one, a whole lunation earlier
      int64_t before = astroPrevMoonPhase(t - 2, q);
      CHECKQ(before < t && t - before > 29 * 86400 && t - before < 30 * 86400,
             "prev %s before %lld: %lld", Q_NAME[q], (long long)t, (long long)before);
    }
  }
  CHECK(roundTrip, "astroPrevMoonPhase(astroNextMoonPhase(t, q), q) returns the same instant");
  // The time scale, end to end: the mean SIGNED error of the 192 quarters is +26.6 s (the
  // low-accuracy sun's longitude, ~0.003 deg); running the moon on UT instead of TT (DELTA_T = 0)
  // makes it +95.6 s while every quarter stays inside the 300 s tolerance. (review 2026-09-27)
  phaseBias /= (double)(N_OF(ALM_PHASES) * 4);
  printf("  quarters: mean signed error %+.1f s\n", phaseBias);
  CHECK(fabs(phaseBias) <= 45.0, "quarters: mean signed error within 45 s (a TT/UT slip is ~69 s)");
  for (size_t r = 0; r < N_OF(ALM_SEASONS); r++) {
    const AlmSeasonVec& v = ALM_SEASONS[r];
    for (int w = 0; w < 4; w++) {
      int64_t t = astroNextSeason(v.from, w);
      double e = fabs((double)(t - v.next[w]));
      note(&wSeason, e, "season", (long long)v.from);
      CHECKQ(e <= 1200, "season %d from %lld: got %lld want %lld (%+lld s)", w, (long long)v.from,
             (long long)t, (long long)v.next[w], (long long)(t - v.next[w]));
    }
  }
  {
    // next strictly after: from the instant itself goes to the following one
    int64_t fm = astroNextMoonPhase(1790812800LL, 2);
    int64_t fm2 = astroNextMoonPhase(fm, 2);
    CHECK(fm2 - fm > 29 * 86400 && fm2 - fm < 30 * 86400, "next full from a full moon is the following one");
    CHECK(astroPrevMoonPhase(fm, 2) == fm, "prev full at a full moon is that full moon");
    int64_t eq = astroNextSeason(1767225600LL, 0);
    CHECK(astroNextSeason(eq, 0) - eq > 364 * 86400, "next March equinox from one is a year on");
  }
  {
    // the phase name at the quarters themselves, and age at a new moon
    AstroMoonPhase p;
    int64_t nm = astroNextMoonPhase(1790812800LL, 0);
    astroMoonPhaseAt(nm + 60, &p);
    CHECK(p.phase == 0 && p.ageDays < 0.01 && p.illum < 0.01, "at new moon: New, age ~0, dark");
    astroMoonPhaseAt(astroNextMoonPhase(nm, 1), &p);
    CHECK(p.phase == 2 && fabs(p.illum - 0.5) < 0.02 && p.sep > 0, "at first quarter: First quarter, half lit, waxing");
    astroMoonPhaseAt(astroNextMoonPhase(nm, 2), &p);
    CHECK(p.phase == 4 && p.illum > 0.98 && p.ageDays > 13.5 && p.ageDays < 16.0, "at full: Full, lit, ~14.8 days old");
    astroMoonPhaseAt(astroNextMoonPhase(nm, 3), &p);
    CHECK(p.phase == 6 && p.sep < 0, "at last quarter: Last quarter, waning");
  }

  // ---- solunar -------------------------------------------------------------------------------
  {
    int64_t nm = astroNextMoonPhase(1790812800LL, 0);      // a new moon in October 2026
    int64_t t0 = nm - 43200;                               // the phase at t0+12h is new
    AstroSunDay sun = { t0 + 22000, t0 + 24000, t0 + 45000, t0 + 66000, t0 + 68000 };
    AstroMoonDay moon = { t0 + 23000, t0 + 66500, t0 + 45000, 0 };  // rise 1000 s before sunrise
    AstroSolunar s;
    astroSolunar(t0, &sun, &moon, &s);
    CHECK(s.nMajor == 1 && s.majorMid[0] == t0 + 45000, "solunar: one major (overhead)");
    CHECK(s.nMinor == 2 && s.minorMid[0] == t0 + 23000 && s.minorMid[1] == t0 + 66500, "solunar: two minors in time order");
    CHECK(s.rating == 4, "solunar: new moon + a period on sunrise = 4 (Excellent)");
    AstroMoonDay far = { t0 + 30000, t0 + 60000, t0 + 45000, 0 };
    astroSolunar(t0, &sun, &far, &s);
    CHECK(s.rating == 3, "solunar: new moon, nothing on sunrise/sunset = 3");
    // majors +-60 min: an underfoot 59 min after sunset counts; 61 min does not
    AstroMoonDay under = { 0, 0, 0, sun.set + 59 * 60 };
    int64_t fq = astroNextMoonPhase(nm, 1);
    int64_t q0 = fq - 43200;
    AstroSunDay qs = { q0 + 22000, q0 + 24000, q0 + 45000, q0 + 66000, q0 + 68000 };
    under.under = qs.set + 59 * 60;
    astroSolunar(q0, &qs, &under, &s);
    CHECK(s.rating == 1 && s.nMajor == 1 && s.nMinor == 0, "solunar: quarter moon, major 59 min after sunset = 1");
    under.under = qs.set + 61 * 60;
    astroSolunar(q0, &qs, &under, &s);
    CHECK(s.rating == 0, "solunar: quarter moon, major 61 min after sunset = 0");
    AstroMoonDay none = { q0 + 40000, q0 + 80000, q0 + 60000, q0 + 15000 };
    astroSolunar(q0, &qs, &none, &s);
    CHECK(s.rating == 0 && s.nMajor == 2 && s.majorMid[0] == q0 + 15000, "solunar: quarter moon with nothing = 0, majors ordered");
    // minors +-30 min: a moonset 29 min before sunset counts
    AstroMoonDay minor = { 0, qs.set - 29 * 60, 0, 0 };
    astroSolunar(q0, &qs, &minor, &s);
    CHECK(s.rating == 1, "solunar: minor 29 min before sunset = +1");
    minor.set = qs.set - 31 * 60;
    astroSolunar(q0, &qs, &minor, &s);
    CHECK(s.rating == 0, "solunar: minor 31 min before sunset = 0");
    // phase bands: full moon + 2 days (~24 deg) = 2, + 4 days (~49 deg) = 1
    int64_t fl = astroNextMoonPhase(nm, 2);
    AstroMoonDay nothing = { 0, 0, 0, 0 };
    AstroSunDay nos = { 0, 0, 0, 0, 0 };
    astroSolunar(fl - 43200, &nos, &nothing, &s);
    CHECK(s.rating == 3, "solunar: full moon day = 3");
    astroSolunar(fl + 2 * 86400 - 43200, &nos, &nothing, &s);
    CHECK(s.rating == 2, "solunar: two days past full = 2");
    astroSolunar(fl + 4 * 86400 - 43200, &nos, &nothing, &s);
    CHECK(s.rating == 1, "solunar: four days past full = 1");
    // The band edges (12, 36, 60 deg, inclusive) half a degree either side, on both sides of new
    // and full, with the phase taken at t0 + 12 h: t0 = the instant the elongation is there - 12 h.
    // (Review 2026-09-27: the 36 band and the t0 + 12 h rule could be broken without a failure.)
    static const double EDGE[6] = { 11.5, 12.5, 35.5, 36.5, 59.5, 60.5 };
    static const int WANT[6] = { 3, 2, 2, 1, 1, 0 };
    bool edges = true;
    for (int side = 0; side < 4; side++) {             // after new, before full, after full, before new
      int64_t ref = side == 0 ? nm : side == 3 ? astroNextMoonPhase(fl, 0) : fl;
      for (int k = 0; k < 6; k++) {
        double target = side == 0 ? EDGE[k] : side == 1 ? 180.0 - EDGE[k] : side == 2 ? 180.0 + EDGE[k] : 360.0 - EDGE[k];
        // walk from the reference toward the target (the elongation moves ~12 deg/day), then
        // bisect: the instant the elongation passes it
        int dir = (side == 0 || side == 2) ? +1 : -1;
        int64_t lo = ref, hi = ref;
        AstroMoonPhase ph;
        for (int step = 0; step < 200; step++) {
          hi = lo + dir * 3600;
          astroMoonPhaseAt(hi, &ph);
          if (wrap180(ph.elong - target) * dir >= 0.0) break;
          lo = hi;
        }
        while (llabs((long long)(hi - lo)) > 1) {
          int64_t mid = lo + (hi - lo) / 2;
          astroMoonPhaseAt(mid, &ph);
          if (wrap180(ph.elong - target) * dir >= 0.0) hi = mid; else lo = mid;
        }
        astroSolunar(hi - 43200, &nos, &nothing, &s);
        if (s.rating != WANT[k]) {
          edges = false;
          printf("  FAIL solunar: elongation %.1f at t0+12h rated %d, want %d\n", target, s.rating, WANT[k]);
        }
      }
    }
    CHECK(edges, "solunar: the 12/36/60 deg band edges, +-0.5 deg, both sides of new and full");
  }

  // ---- report ---------------------------------------------------------------------------------
  printf("worst errors against the vectors:\n");
  for (int e = 0; e < EV_N; e++) printWorst(&wEv[e], e < EV_MRISE ? 60 : 120);
  printWorst(&wMoonAlt, 0.1);
  printWorst(&wMoonAz, 0.2);
  printWorst(&wSunAlt, 0.05);
  printWorst(&wSunAz, 0.05);
  printWorst(&wIllum, 0.005);
  printWorst(&wSep, 0.1);
  printWorst(&wAge, 1.5);
  printWorst(&wPhase, 300);
  printWorst(&wSeason, 1200);

  // ---- the day as a job, in slices: bit-identical however it is cut (A1, 2026-09-27) ----------
  {
    /* Phone 2 measured the core day at 148 ms in ONE loop pass (160 MHz). The Almanac now runs
     * astroSunDay / astroMoonDay as an AstroDayJob a slice per timer tick; the one-call functions
     * ARE that job run whole. Cut after every unit, and at random, over 8 places (the poles'
     * edges included) and a year of days: every event the same second. */
    const double P[8][2] = { { 47.4957, -121.7868 }, { 71.2906, -156.7887 }, { -0.1807, -78.4678 },
                             { -33.8688, 151.2093 }, { 78.2232, 15.6267 }, { 22.5726, 88.3639 },
                             { 89.9, 0.0 }, { -78.0, 166.0 } };
    struct Cut { unsigned seed; int left; int units; };
    struct F {
      static bool more(void* c) {
        Cut* k = (Cut*)c;
        k->units++;
        if (k->left-- > 0) return true;
        k->seed = k->seed * 1103515245u + 12345u;
        k->left = (int)((k->seed >> 16) % 40);
        return false;
      }
      static bool never(void* c) { ((Cut*)c)->units++; return false; }
    };
    bool same = true, progress = true;
    long days = 0, maxUnits = 0;
    for (int p = 0; p < 8; p++) {
      for (int d = 0; d < 366; d += 5) {
        const int64_t t0 = astroDaysFromCivil(2026, 1, 1) * 86400 + (int64_t)d * 86400 + 25200 - p * 3600;
        for (int body = 0; body < 2; body++) {
          AstroSunDay s1, s2, s3;
          AstroMoonDay m1, m2, m3;
          AstroDayJob j;
          Cut rnd = { (unsigned)(p * 977 + d), 0, 0 }, one = { 0, 0, 0 };
          // cut at random
          astroDayJobStart(&j, body, t0, P[p][0], P[p][1]);
          while (!astroDayJobRun(&j, F::more, &rnd)) {}
          if (body == ASTRO_BODY_SUN) astroDayJobSun(&j, &s2); else astroDayJobMoon(&j, &m2);
          // one unit per call: more() always says stop, and each call still makes progress
          astroDayJobStart(&j, body, t0, P[p][0], P[p][1]);
          int calls = 0;
          while (!astroDayJobRun(&j, F::never, &one) && calls < 5000) calls++;
          progress = progress && astroDayJobDone(&j) && astroDayJobRun(&j, F::never, &one);
          if (calls + 1 > maxUnits) maxUnits = calls + 1;
          if (body == ASTRO_BODY_SUN) {
            astroDayJobSun(&j, &s3);
            astroSunDay(t0, P[p][0], P[p][1], &s1);
            same = same && !memcmp(&s1, &s2, sizeof(s1)) && !memcmp(&s1, &s3, sizeof(s1));
          } else {
            astroDayJobMoon(&j, &m3);
            astroMoonDay(t0, P[p][0], P[p][1], &m1);
            same = same && !memcmp(&m1, &m2, sizeof(m1)) && !memcmp(&m1, &m3, sizeof(m1));
          }
          days++;
        }
      }
    }
    char msg[160];
    snprintf(msg, sizeof(msg), "day job: %ld sun/moon days, cut at random and after every unit (%ld units a day), "
             "= astroSunDay/astroMoonDay to the second", days, maxUnits);
    CHECK(same, msg);
    CHECK(progress, "day job: every call makes progress (at least one unit), and a done job stays done");
    CHECK(maxUnits == 9 + 1 + 288, "day job: 9 nodes + the first sample + 288 five-minute samples");

    // astroMoonPhaseWith(t, the search's answer) IS astroMoonPhaseAt(t); 0 = no age.
    bool ph = true;
    for (int k = 0; k < 400; k++) {
      const int64_t t = 1780000000LL + (int64_t)k * 21601;
      AstroMoonPhase a, b, z;
      astroMoonPhaseAt(t, &a);
      astroMoonPhaseWith(t, astroPrevMoonPhase(t, 0), &b);
      astroMoonPhaseWith(t, 0, &z);
      ph = ph && a.elong == b.elong && a.sep == b.sep && a.illum == b.illum && a.phase == b.phase &&
           a.ageDays == b.ageDays && z.illum == a.illum && z.phase == a.phase && z.ageDays == 0.0;
    }
    CHECK(ph, "phase: astroMoonPhaseWith(t, prev new moon) == astroMoonPhaseAt(t) at 400 instants; 0 = no age");
  }

  // ---- cost: one Almanac screen's worth ------------------------------------------------------
  {
    const int RUNS = 200;
    volatile int64_t sink = 0;
    clock_t c0 = clock();
    for (int i = 0; i < RUNS; i++) {
      int64_t t0 = 1790838000LL + (int64_t)i * 86400;
      AstroSunDay s;
      AstroMoonDay mo;
      astroSunDay(t0, 47.4957, -121.7868, &s);
      astroMoonDay(t0, 47.4957, -121.7868, &mo);
      for (int q = 0; q < 4; q++) sink = sink + astroNextMoonPhase(t0, q);
      sink = sink + s.rise + mo.rise;
    }
    double us = (double)(clock() - c0) / CLOCKS_PER_SEC * 1e6 / RUNS;
    printf("  cost: astroSunDay + astroMoonDay + 4 x astroNextMoonPhase = %.0f us on this host (ASan build)\n", us);
  }

  printf("test_almanac: %d checks, %d failures\n", checks, failures);
  return failures;
}
