/*
 * test_jpeg.cpp — the greyscale JPEG decoder, against a reference decoder.
 *
 * A decoder that is subtly wrong is worse than none: it draws confident rubbish instead of
 * saying it cannot. So this does not eyeball shapes — it decodes real pictures out of the
 * real book and compares EVERY PIXEL against macOS `sips`, which is a completely independent
 * implementation shipped with the OS.
 *
 * Exact equality is not the bar. Different IDCT implementations legitimately differ by a
 * count or two on some pixels; what would show a real bug is a block in the wrong place, a
 * mis-decoded coefficient or a lost restart marker, and any of those move pixels by tens or
 * hundreds. The check is therefore: mean error under 1, and no pixel off by more than 4.
 *
 * The fixtures are generated by tools/gen_jpeg_fixtures.sh, which extracts the images from
 * the EPUB and renders the references with sips. They are NOT committed: the book is bought,
 * and this repo is public. Without them the suite skips this file and says so.
 */
#include "../WiPhone/jpeg_grey.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int g_pass = 0, g_fail = 0;
static const char* g_group = "";

static void group(const char* name) {
  g_group = name;
  printf("\n\033[1m%s\033[0m\n", name);
}

static void ok(bool cond, const char* what) {
  if (cond) {
    g_pass++;
  } else {
    g_fail++;
    printf("  \033[31mFAIL\033[0m %s :: %s\n", g_group, what);
  }
}

// ---------------------------------------------------------------- a tiny PGM/PNG-ish reader
// The reference is written as binary PGM (P5) by the fixture script — sips makes a PNG and
// the script converts it, so nothing here needs an image library.
static uint8_t* readPGM(const char* path, int* w, int* h) {
  FILE* f = fopen(path, "rb");
  if (!f) {
    return NULL;
  }
  char magic[3] = {0};
  int maxv = 0;
  if (fscanf(f, "%2s", magic) != 1 || strcmp(magic, "P5") != 0) {
    fclose(f);
    return NULL;
  }
  // Skip comments between fields.
  int vals[3], got = 0;
  while (got < 3) {
    int c = fgetc(f);
    if (c == '#') {
      while (c != '\n' && c != EOF) {
        c = fgetc(f);
      }
      continue;
    }
    if (c == EOF) {
      fclose(f);
      return NULL;
    }
    if (c == ' ' || c == '\n' || c == '\r' || c == '\t') {
      continue;
    }
    ungetc(c, f);
    if (fscanf(f, "%d", &vals[got]) != 1) {
      fclose(f);
      return NULL;
    }
    got++;
  }
  *w = vals[0];
  *h = vals[1];
  maxv = vals[2];
  fgetc(f);                                   // the single whitespace before the data
  if (maxv != 255 || *w <= 0 || *h <= 0) {
    fclose(f);
    return NULL;
  }
  size_t n = (size_t)(*w) * (size_t)(*h);
  uint8_t* px = (uint8_t*)malloc(n);
  size_t rd = fread(px, 1, n, f);
  fclose(f);
  if (rd != n) {
    free(px);
    return NULL;
  }
  return px;
}

static uint8_t* readFile(const char* path, size_t* lenOut) {
  FILE* f = fopen(path, "rb");
  if (!f) {
    return NULL;
  }
  fseek(f, 0, SEEK_END);
  long n = ftell(f);
  fseek(f, 0, SEEK_SET);
  uint8_t* b = (uint8_t*)malloc((size_t)n);
  size_t rd = fread(b, 1, (size_t)n, f);
  fclose(f);
  if (rd != (size_t)n) {
    free(b);
    return NULL;
  }
  *lenOut = (size_t)n;
  return b;
}

// ---------------------------------------------------------------- collect decoded rows
struct Sink {
  uint8_t* px;
  int w, h;
};

static void sinkRows(void* ctx, int y0, int rows, const uint8_t* band, int width) {
  Sink* s = (Sink*)ctx;
  for (int y = 0; y < rows; y++) {
    int dy = y0 + y;
    if (dy >= s->h) {
      break;
    }
    int n = width < s->w ? width : s->w;     // the band is padded out to whole blocks
    memcpy(s->px + (size_t)dy * s->w, band + (size_t)y * width, (size_t)n);
  }
}

/* `tol` differs by fixture and the reason matters:
 *
 *   truth.jpg  — pixels WE chose, encoded at quality 100. The right answer is known, so this
 *                is exact-ish and is the real correctness test.
 *   grey*.jpg  — real pictures from the book, compared against macOS sips. An independent
 *                decoder is a good cross-check for structural faults (a block in the wrong
 *                place moves pixels by tens), but not for the last count or two: sips renders
 *                a low-quality JPEG with its own smoothing, which shows up as a smooth S-curve
 *                of midtone differences at sharp edges. Verified against the ground-truth
 *                fixture that the difference is sips' choice and not ours.
 */
static void compare(const char* jpg, const char* pgm, double meanTol, int worstTol) {
  size_t len = 0;
  uint8_t* data = readFile(jpg, &len);
  if (!data) {
    printf("  (skipped: no %s)\n", jpg);
    return;
  }
  int rw = 0, rh = 0;
  uint8_t* ref = readPGM(pgm, &rw, &rh);
  if (!ref) {
    printf("  (skipped: no reference %s)\n", pgm);
    free(data);
    return;
  }

  char what[160];
  ok(jpegGreyIsGreyBaseline(data, len), "recognised as baseline greyscale");

  uint16_t w = 0, h = 0;
  Sink s = { NULL, 0, 0 };
  // First pass just for the dimensions, so the sink can be sized.
  jpegGreyDecode(data, len, NULL, NULL, &w, &h);
  snprintf(what, sizeof(what), "%s: size %ux%u matches the reference %dx%d", jpg, w, h, rw, rh);
  ok(w == rw && h == rh, what);
  if (w != rw || h != rh) {
    free(data);
    free(ref);
    return;
  }

  s.w = rw;
  s.h = rh;
  s.px = (uint8_t*)calloc((size_t)rw * rh, 1);
  JpegGreyStatus st = jpegGreyDecode(data, len, sinkRows, &s, &w, &h);
  snprintf(what, sizeof(what), "%s: decodes (%s)", jpg, jpegGreyStatusText(st));
  ok(st == JPEG_GREY_OK, what);

  if (st == JPEG_GREY_OK) {
    double sum = 0;
    int worst = 0;
    size_t n = (size_t)rw * rh;
    for (size_t k = 0; k < n; k++) {
      int d = (int)s.px[k] - (int)ref[k];
      if (d < 0) {
        d = -d;
      }
      sum += d;
      if (d > worst) {
        worst = d;
      }
    }
    double mean = sum / (double)n;
    snprintf(what, sizeof(what), "%s: mean error %.3f < %.2f", jpg, mean, meanTol);
    ok(mean < meanTol, what);
    snprintf(what, sizeof(what), "%s: worst pixel off by %d <= %d", jpg, worst, worstTol);
    ok(worst <= worstTol, what);
    if (mean >= meanTol || worst > worstTol) {
      printf("    (a block in the wrong place or a lost restart marker moves pixels by"
             " tens; rounding does not)\n");
    }
  }

  free(s.px);
  free(ref);
  free(data);
}

static void testRefusals() {
  group("what it refuses, it refuses clearly");

  // A colour JPEG: the ROM decoder handles those, and this one must not pretend to.
  size_t len = 0;
  uint8_t* colour = readFile("tests/fixtures/jpeg/colour.jpg", &len);
  if (colour) {
    ok(!jpegGreyIsGreyBaseline(colour, len), "a colour JPEG is not claimed");
    uint16_t w = 0, h = 0;
    JpegGreyStatus st = jpegGreyDecode(colour, len, NULL, NULL, &w, &h);
    ok(st == JPEG_GREY_ERR_UNSUPPORTED, "and decoding it says unsupported, not garbage");
    ok(w > 0 && h > 0, "though its size is still reported, for the caller's message");
    free(colour);
  } else {
    printf("  (skipped: no colour fixture)\n");
  }

  const uint8_t junk[64] = { 0 };
  uint16_t w = 0, h = 0;
  ok(jpegGreyDecode(junk, sizeof(junk), NULL, NULL, &w, &h) == JPEG_GREY_ERR_NOT_JPEG,
     "junk is not a JPEG");
  ok(!jpegGreyIsGreyBaseline(junk, sizeof(junk)), "and is not claimed");
  ok(jpegGreyDecode(NULL, 0, NULL, NULL, &w, &h) == JPEG_GREY_ERR_NOT_JPEG, "nor is nothing");

  // Truncated: must fail rather than read off the end. ASan is the real assertion here.
  size_t glen = 0;
  uint8_t* g = readFile("tests/fixtures/jpeg/grey1.jpg", &glen);
  if (g) {
    for (size_t cut = 8; cut < glen; cut = cut * 2) {
      uint16_t tw = 0, th = 0;
      jpegGreyDecode(g, cut, NULL, NULL, &tw, &th);      // must not crash or overrun
    }
    ok(true, "truncated at every power of two: no overrun (ASan would have said)");
    free(g);
  }
}

int main() {
  /* Known pixels first: this is the one with an actual right answer. A checkerboard of hard
   * 8px edges is the worst case for ringing, so if the IDCT, dequantisation or coefficient
   * order were wrong at all, it would show here before anywhere else. */
  group("decoded pixels vs KNOWN pixels (quality 100 round trip)");
  compare("tests/fixtures/jpeg/truth.jpg", "tests/fixtures/jpeg/truth.pgm", 0.05, 2);

  group("and vs macOS sips, on real pictures from the book");
  compare("tests/fixtures/jpeg/grey1.jpg", "tests/fixtures/jpeg/grey1.pgm", 2.0, 40);
  compare("tests/fixtures/jpeg/grey2.jpg", "tests/fixtures/jpeg/grey2.pgm", 2.0, 40);
  testRefusals();

  if (g_pass == 0 && g_fail == 0) {
    printf("\n\033[33mno fixtures: run tools/gen_jpeg_fixtures.sh with the EPUB\033[0m\n");
    return 0;
  }
  printf("\n%s%d passed, %d failed\033[0m\n", g_fail ? "\033[31m" : "\033[32m", g_pass, g_fail);
  return g_fail ? 1 : 0;
}
