/*
 * test_mp3.cpp — the MP3 path, decoding a real track with the real decoder.
 *
 * This compiles helix itself (portable C, no assembly on this target) along with the
 * stream layer, so a pass proves the bytes that ship are the bytes that decode. Nothing
 * here needs the phone.
 *
 * Everything in this layer fails SILENTLY on the device, which is why it is tested at
 * all. A mis-read ID3 size seeks past the start of the song. A sync word found inside
 * album art starts playback halfway through a JPEG. Neither crashes; both just sound
 * wrong, on a device with no debugger and no console.
 *
 * The fixture is a slice of a real track, generated by tools/gen_mp3_fixtures.sh and
 * NOT committed — the repo is public and the music is not ours. Without it this file
 * skips the decode tests and says so; the pure-logic tests still run.
 */
#include "../WiPhone/mp3_stream.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int g_pass = 0, g_fail = 0;
static const char* g_group = "";

static void group(const char* name) {
  g_group = name;
  printf("\n\033[1m%s\033[0m\n", name);
}

static void ok(bool cond, const char* what) {
  if (cond) {
    g_pass++;
  } else {
    g_fail++;
    printf("  \033[31mFAIL\033[0m %s :: %s\n", g_group, what);
  }
}

// ───────────────────────────────────────────────────────── ID3

static void testId3() {
  group("skipping the ID3 tag");

  uint8_t t[10];
  memset(t, 0, sizeof(t));
  t[0] = 'I';
  t[1] = 'D';
  t[2] = '3';
  t[3] = 3;

  /* The whole point of syncsafe: 7 bits per byte. 0x00 0x00 0x02 0x01 is 257, NOT the
   * 513 a plain big-endian read would give. Every tag over 128 bytes — i.e. every real
   * one — differs between the two readings, and the wrong one seeks past the song. */
  t[6] = 0x00;
  t[7] = 0x00;
  t[8] = 0x02;
  t[9] = 0x01;
  ok(mp3Id3v2Size(t, 10) == 257 + 10, "syncsafe size is 7 bits per byte, not 8");

  t[6] = 0x00;
  t[7] = 0x01;
  t[8] = 0x00;
  t[9] = 0x00;
  ok(mp3Id3v2Size(t, 10) == 16384 + 10, "a big tag (album art) reads correctly");

  // Footer flag (bit 4 of the flags byte) adds another 10 bytes.
  t[5] = 0x10;
  ok(mp3Id3v2Size(t, 10) == 16384 + 20, "a footer adds ten more");
  t[5] = 0x00;

  // A high bit set anywhere in the size means it is not a valid syncsafe field.
  t[8] = 0x80;
  ok(mp3Id3v2Size(t, 10) == 0, "a set high bit means the size is not trustworthy");
  t[8] = 0x02;

  const uint8_t noTag[10] = { 0xFF, 0xFB, 0x90, 0x00, 0, 0, 0, 0, 0, 0 };
  ok(mp3Id3v2Size(noTag, 10) == 0, "a file that starts with audio has no tag to skip");

  ok(mp3Id3v2Size(t, 4) == 0, "a short buffer is safe");
  ok(mp3Id3v2Size(NULL, 10) == 0, "a null buffer is safe");
}

// ───────────────────────────────────────────────────────── sync

static void testSync() {
  group("finding a real frame, not a false one");

  // A valid MPEG-1 Layer III header: 0xFF 0xFB = sync + MPEG1 + Layer III + no CRC.
  uint8_t buf[64];
  memset(buf, 0, sizeof(buf));
  buf[8] = 0xFF;
  buf[9] = 0xFB;
  buf[10] = 0x90;   // bitrate index 9, sample rate index 0 (44100)
  buf[11] = 0x00;
  ok(mp3FindFrame(buf, sizeof(buf), 0) == 8, "finds a valid header");
  ok(mp3FindFrame(buf, sizeof(buf), 9) == -1, "does not find it when starting past it");

  /* False positives are the real hazard: eleven set bits occur constantly inside album
   * art. Each of these has the sync bits but is invalid further in, and must be rejected
   * — otherwise playback starts halfway through a JPEG. */
  uint8_t bad[16];
  memset(bad, 0, sizeof(bad));
  bad[0] = 0xFF;
  bad[1] = 0xEB;          // MPEG version 01 = reserved
  bad[2] = 0x90;
  ok(mp3FindFrame(bad, sizeof(bad), 0) == -1, "reserved MPEG version rejected");

  bad[1] = 0xF9;          // layer 00 = reserved
  ok(mp3FindFrame(bad, sizeof(bad), 0) == -1, "reserved layer rejected");

  bad[1] = 0xFB;
  bad[2] = 0xF0;          // bitrate index 0x0F = `bad`
  ok(mp3FindFrame(bad, sizeof(bad), 0) == -1, "`bad` bitrate index rejected");

  bad[2] = 0x00;          // bitrate index 0 = `free`
  ok(mp3FindFrame(bad, sizeof(bad), 0) == -1, "`free` bitrate index rejected");

  bad[2] = 0x9C;          // sample rate index 3 = reserved
  ok(mp3FindFrame(bad, sizeof(bad), 0) == -1, "reserved sample rate rejected");

  ok(mp3FindFrame(NULL, 16, 0) == -1, "null is safe");
  ok(mp3FindFrame(bad, 2, 0) == -1, "a buffer shorter than a header is safe");
}

// ───────────────────────────────────────────────────────── the real thing

static uint8_t* readFile(const char* path, size_t* len) {
  FILE* f = fopen(path, "rb");
  if (!f) {
    return NULL;
  }
  fseek(f, 0, SEEK_END);
  long n = ftell(f);
  fseek(f, 0, SEEK_SET);
  if (n <= 0) {
    fclose(f);
    return NULL;
  }
  uint8_t* b = (uint8_t*)malloc((size_t)n);
  if (!b) {
    fclose(f);
    return NULL;
  }
  size_t got = fread(b, 1, (size_t)n, f);
  fclose(f);
  *len = got;
  return b;
}

static void testDecode() {
  group("decoding a real track");

  size_t len = 0;
  uint8_t* file = readFile("tests/fixtures/mp3/track.mp3", &len);
  if (!file) {
    printf("  \033[33mSKIP\033[0m no fixture — run tools/gen_mp3_fixtures.sh <file.mp3>\n");
    return;
  }

  Mp3Stream s;
  ok(s.begin(), "the decoder allocates");
  ok(s.ready(), "and reports ready");

  // Skip the ID3 tag exactly as the app will.
  uint32_t start = mp3Id3v2Size(file, len);
  ok(start > 0, "the fixture has an ID3 tag (so the skip is exercised)");
  ok(start < len, "and the tag does not swallow the whole slice");

  int16_t pcm[MP3_MAX_FRAME_SAMPLES];
  Mp3Info info;
  memset(&info, 0, sizeof(info));

  size_t pos = start;
  int frames = 0, samples = 0, bad = 0;
  bool nonSilent = false;

  while (pos < len && frames < 200) {
    size_t room = s.space();
    if (room > 0) {
      size_t take = len - pos;
      if (take > room) {
        take = room;
      }
      pos += s.fill(file + pos, take);
    }
    int n = s.decode(pcm, &info);
    if (n > 0) {
      frames++;
      samples += n;
      for (int i = 0; i < n; i++) {
        if (pcm[i] > 256 || pcm[i] < -256) {
          nonSilent = true;
        }
      }
    } else if (n < 0) {
      bad++;
    } else if (pos >= len) {
      break;                      // needs more input and there is none
    }
  }

  ok(frames > 50, "decodes many frames in a row");
  ok(bad == 0, "with no corrupt frames in a clean file");
  ok(s.haveFormat(), "and reports the format");

  /* The format has to be RIGHT, not merely present: these drive the I2S clock and the
   * channel layout, and getting them wrong plays the track at the wrong speed. */
  ok(info.sampleRate == 44100 || info.sampleRate == 48000 || info.sampleRate == 32000,
     "a real sample rate");
  ok(info.channels == 1 || info.channels == 2, "a real channel count");
  ok(info.bitrate > 0, "a real bitrate");

  /* 1152 samples per channel is the MPEG-1 Layer III frame size, and it is exactly what
   * Audio::playDec is sized to hold. If this ever stops being true, that buffer is too
   * small and the overflow would be silent. */
  ok(info.outputSamps == 1152 * info.channels, "one frame is 1152 samples per channel");
  ok(info.outputSamps <= MP3_MAX_FRAME_SAMPLES, "and fits the frame buffer");

  ok(nonSilent, "the audio is not silence (the decoder actually decoded)");
  ok(samples > frames * 100, "and produced a sensible amount of it");

  printf("  \033[2m%d frames, %d samples, %d Hz, %d ch, %d kbps\033[0m\n",
         frames, samples, info.sampleRate, info.channels, info.bitrate / 1000);

  /* A corrupt file must degrade, not die. MP3 is designed to resynchronise and a damaged
   * download should cost a crackle rather than the rest of the album. */
  Mp3Stream junkS;
  junkS.begin();
  uint8_t junk[2048];
  for (size_t i = 0; i < sizeof(junk); i++) {
    junk[i] = (uint8_t)(i * 37 + 11);
  }
  junkS.fill(junk, sizeof(junk));
  int guard = 0;
  while (guard++ < 100) {
    if (junkS.decode(pcm, &info) == 0) {
      break;
    }
  }
  ok(guard < 100, "random bytes are rejected rather than looping forever");

  s.end();
  ok(!s.ready(), "and it frees cleanly");
  free(file);
}

int main() {
  testId3();
  testSync();
  testDecode();

  printf("\n%s%d passed, %d failed\033[0m\n",
         g_fail ? "\033[31m" : "\033[32m", g_pass, g_fail);
  return g_fail ? 1 : 0;
}
