/* GENERATED by tools/gen_epub_vectors.py from COVEY's epub.py — do not edit. */
#pragma once

typedef struct { const char* in; const char* want; } EpStrVec;
static const EpStrVec EP_SLUG_VECS[] = {
  { "Pride and Prejudice", "pride-and-prejudice" },
  { "  Leading and trailing  ", "leading-and-trailing" },
  { "MiXeD CaSe 123", "mixed-case-123" },
  { "punctuation!!!  everywhere???", "punctuation-everywhere" },
  { "---dashes---", "dashes" },
  { "", "" },
  { "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" },
  { "The Long & Winding Road|Ada Lovelace", "the-long-winding-road-ada-lovelace" },
  { "9780000000001", "9780000000001" },
};
static const int EP_SLUG_VEC_N = 9;

typedef struct { const char* base; const char* href; const char* want; } EpNormVec;
static const EpNormVec EP_NORM_VECS[] = {
  { "", "ch1.xhtml", "ch1.xhtml" },
  { "OEBPS", "text/one.xhtml", "OEBPS/text/one.xhtml" },
  { "OEBPS", "../root.xhtml", "root.xhtml" },
  { "OEBPS/text", "../images/x.png", "OEBPS/images/x.png" },
  { "OEBPS", "./same.xhtml", "OEBPS/same.xhtml" },
  { "", "a/b/../c.xhtml", "a/b/../c.xhtml" },
  { "OEBPS", "one.xhtml#frag", "OEBPS/one.xhtml" },
  { "", "with#frag.xhtml", "with" },
};
static const int EP_NORM_VEC_N = 8;

static const EpStrVec EP_HTML_VECS[] = {
  /* simple */ { "<p>Hello world</p>", "Hello world" },
  /* two-paras */ { "<p>One</p><p>Two</p>", "One\n\nTwo" },
  /* collapse */ { "<p>  lots   of \n\n whitespace  </p>", "lots of whitespace" },
  /* heading */ { "<h1>Title</h1><p>Body text</p>", "Title\n\nBody text" },
  /* drop-script */ { "<p>Keep</p><script>var drop = 1;</script><p>This</p>", "Keep\n\nThis" },
  /* drop-style */ { "<style>p{color:red}</style><p>Only me</p>", "Only me" },
  /* nested */ { "<div><p>Inner <em>emphasis</em> here</p></div>", "Inner emphasis here" },
  /* br */ { "<p>Line one<br/>Line two</p>", "Line one\n\nLine two" },
  /* entities */ { "<p>Tom &amp; Jerry &lt;3 &quot;quotes&quot;</p>", "Tom & Jerry <3 \"quotes\"" },
  /* numeric-ent */ { "<p>caf&#233; and &#x2014; dash</p>", "caf\xc3""\xa9"" and \xe2""\x80""\x94"" dash" },
  /* list */ { "<ul><li>alpha</li><li>beta</li></ul>", "alpha\n\nbeta" },
  /* empty */ { "<p></p><p>   </p><p>real</p>", "real" },
  /* no-tags */ { "just bare text", "just bare text" },
  /* comment */ { "<p>before</p><!-- a comment --><p>after</p>", "before\n\nafter" },
  /* table */ { "<table><tr><td>a</td><td>b</td></tr></table>", "a\n\nb" },
  /* ent-punct */ { "<p>Wait&hellip; &ldquo;really&rdquo; &mdash; yes&nbsp;indeed.</p>", "Wait\xe2""\x80""\xa6"" \xe2""\x80""\x9c""really\xe2""\x80""\x9d"" \xe2""\x80""\x94"" yes indeed." },
  /* ent-accents */ { "<p>na&iuml;ve caf&eacute; r&eacute;sum&eacute; &Uuml;ber stra&szlig;e</p>", "na\xc3""\xaf""ve caf\xc3""\xa9"" r\xc3""\xa9""sum\xc3""\xa9"" \xc3""\x9c""ber stra\xc3""\x9f""e" },
  /* ent-symbols */ { "<p>&copy; 2026 &middot; &dagger; &sect; &para; &frac12; &times; &pound;</p>", "\xc2""\xa9"" 2026 \xc2""\xb7"" \xe2""\x80""\xa0"" \xc2""\xa7"" \xc2""\xb6"" \xc2""\xbd"" \xc3""\x97"" \xc2""\xa3""" },
  /* ent-greek */ { "<p>&alpha; &beta; &Omega; &pi; &mu;</p>", "\xce""\xb1"" \xce""\xb2"" \xce""\xa9"" \xcf""\x80"" \xce""\xbc""" },
  /* ent-longname */ { "<p>&CounterClockwiseContourIntegral; and &InvisibleTimes; end</p>", "\xe2""\x88""\xb3"" and \xe2""\x81""\xa2"" end" },
  /* ent-unknown */ { "<p>not an entity: &zzznotreal; stays put</p>", "not an entity: &zzznotreal; stays put" },
  /* ent-dense */ { "<p>&lsquo;a&rsquo;&mdash;&lsquo;b&rsquo;&hellip;&lsquo;c&rsquo;</p>", "\xe2""\x80""\x98""a\xe2""\x80""\x99""\xe2""\x80""\x94""\xe2""\x80""\x98""b\xe2""\x80""\x99""\xe2""\x80""\xa6""\xe2""\x80""\x98""c\xe2""\x80""\x99""" },
};
static const int EP_HTML_VEC_N = 22;

typedef struct {
  const char* label; const char* file; const char* displayName; int isText;
  const char* title; const char* author; const char* identifier;
  const char* ids[3]; int nIds;
  const char* spine[16]; int nSpine;
  const char* chapTitle[16];
  const char* chapter0;
  double fractionMid; int locateSpine;
} EpBookVec;
static const EpBookVec EP_BOOK_VECS[] = {
  { "epub3_nav", "epub3-nav.epub", "epub3-nav.epub", 0,
    "The Long & Winding Road", "Ada Lovelace", "urn:uuid:12345678-ABCD",
    { "id:urn-uuid-12345678-abcd", "ta:the-long-winding-road-ada-lovelace", "fp:15c2fbb9bece75ce" }, 3,
    { "ch1.xhtml", "ch2.xhtml" }, 2,
    { "Opening", "The Middle" },
    "Opening\n\nIt was a bright cold day.\n\nThe clocks were striking & thirteen.", 0.25, 1 },
  { "epub2_subdir", "epub2-subdir.epub", "epub2-subdir.epub", 0,
    "Deep In A Folder", "Grace Hopper", "isbn:9780000000001",
    { "id:isbn-9780000000001", "ta:deep-in-a-folder-grace-hopper", "fp:f221b7a543a08aea" }, 3,
    { "OEBPS/text/one.xhtml", "OEBPS/text/two.xhtml" }, 2,
    { "Chapter One", "Chapter Two" },
    "One\n\nDown in a subdirectory.", 0.25, 1 },
  { "empty_spine", "empty-spine.epub", "empty-spine.epub", 0,
    "No Spine At All", "", "",
    { "ta:no-spine-at-all", "fp:f20ce8ee9a8d296a" }, 2,
    { "only.xhtml" }, 1,
    { "Chapter 1" },
    "Only\n\nThe one and only chapter.", 0.4838709677419355, 0 },
  { "no_metadata", "no-metadata.epub", "no-metadata.epub", 0,
    "no-metadata", "", "",
    { "ta:no-metadata", "fp:25024515d8425f7b" }, 2,
    { "c.xhtml" }, 1,
    { "Chapter 1" },
    "C\n\nAnonymous book.", 0.5, 0 },
  { "plain_txt", "my-notes.txt", "my-notes.txt", 1,
    "my-notes", "", "",
    { "ta:my-notes", "fp:6c5ac77702fc000e" }, 2,
    { "my-notes.txt" }, 1,
    { "my-notes" },
    "First paragraph of the notes.\n\nSecond paragraph here.", 0.49056603773584906, 0 },
};
static const int EP_BOOK_VEC_N = 5;

