/* GENERATED by tools/gen_booksync_vectors.py from COVEY's booksync.py — do not edit.
 *
 * Ground truth for the WiPhone's C++ port. Every string here was produced by running
 * COVEY's real implementation, so a test failure means the two devices would have
 * silently failed to sync on air.
 *
 * booksync.py VERSION=1  MAC_LEN=10  KDF_SALT=covey-booksync-v1  MESH_PREFIX=CBS1
 */
#pragma once

typedef struct { const char* label; const char* passcode; const char* keyHex; } BsKeyVec;

typedef struct {
  const char* label;
  const char* ids[4];
  int         nIds;
  unsigned    spine;
  unsigned    offset;
  double      fraction;
  unsigned    turnedAt;
  const char* dev;
  const char* nonce;
  const char* passcode;
  const char* canonical;      /* _canonical(rec) of the FULL record */
  const char* mac;            /* sign(rec, key) of the FULL record  */
  const char* reducedCanon;   /* _canonical(reduce_for_mesh(rec))   */
  const char* reducedId;      /* the single id a mesh packet carries */
  const char* reducedDev;
  unsigned    reducedSpine;
  unsigned    reducedOffset;
  unsigned    reducedFrQ;     /* fraction quantised to 1/65535ths   */
  const char* meshText;       /* full 'CBS1 <payload> <mac>' packet */
} BsRecVec;

static const BsKeyVec BS_KEY_VECS[] = {
  { "empty", "", "28515107d0809cdc0012adaeb7ab3e5332ba4ebcb0cb8fb54728cb424e8bfffc" },
  { "vec-a", "vector-passcode-a", "9b7eaf296564920478f7fce9b971e4055bd22a611f3babf40b150139fca7789d" },
  { "vec-b", "vector-passcode-b", "0d350b9bc2209d03ceacfff5c4b468c5b6dc939542894e89087fb8876f91f842" },
  { "digits", "0000", "1d1645a13a26db7a9e54da27c9a401d04d85dcec2f06500b9fd9c674eba4cb32" },
  { "longpw", "a much longer passphrase with spaces 12345", "548db2d876820485a1d80a902635816e831b68a86d00882bade89f6b836c633c" },
};
static const int BS_KEY_VEC_N = 5;

static const BsRecVec BS_REC_VECS[] = {
  { "plain",
    { "id:pg-1342", "ta:pride-and-prejudice-jane-austen", "fp:0123456789abcdef", 0 }, 3,
    7u, 4213u, 0.3125, 1754870400u,
    "COVEY", "deadbeef", "vector-passcode-a",
    "1|id:pg-1342,ta:pride-and-prejudice-jane-austen,fp:0123456789abcdef|7|4213|0.312500|1754870400|COVEY|deadbeef",
    "QUZLIVOJHTTBGVK4",
    "1|id:pg-1342|7|4213|0.312490|1754870400|COVEY|deadbeef",
    "id:pg-1342", "COVEY",
    7u, 4213u, 20479u,
    "CBS1 AEAAOAAACB2WRGJSQBH76BKDJ5LEKWIKNFSDU4DHFUYTGNBS32W353Y 6SC6KQKLFKTEY4BN" },
  { "start",
    { "ta:moby-dick-herman-melville", "fp:aabbccdd00112233", 0 }, 2,
    0u, 0u, 0.0, 1700000000u,
    "WiPhone", "00000000", "vector-passcode-a",
    "1|ta:moby-dick-herman-melville,fp:aabbccdd00112233|0|0|0.000000|1700000000|WiPhone|00000000",
    "ETLLG337BRJONDTX",
    "1|ta:moby-dick-herman-melville|0|0|0.000000|1700000000|WiPhone|00000000",
    "ta:moby-dick-herman-melville", "WiPhone",
    0u, 0u, 0u,
    "CBS1 AEAAAAAAAAAGKU7RAAAAAB2XNFIGQ33OMUOHIYJ2NVXWE6JNMRUWG2ZNNBSXE3LBNYWW2ZLMOZUWY3DFAAAAAAA 75ZUTR3P2MZFAUHT" },
  { "end",
    { "id:urn-uuid-9f8e7d6c", "fp:ffeeddccbbaa9988", 0 }, 2,
    412u, 4294967295u, 1.0, 4294967295u,
    "T-Deck", "ffffffff", "vector-passcode-a",
    "1|id:urn-uuid-9f8e7d6c,fp:ffeeddccbbaa9988|412|4294967295|1.000000|4294967295|T-Deck|ffffffff",
    "EOTBCSWH6WOJWYZ7",
    "1|id:urn-uuid-9f8e7d6c|412|4294967295|1.000000|4294967295|T-Deck|ffffffff",
    "id:urn-uuid-9f8e7d6c", "T-Deck",
    412u, 4294967295u, 65535u,
    "CBS1 AEAZZ7777777777777776BSUFVCGKY3LCRUWIOTVOJXC25LVNFSC2OLGHBSTOZBWMP777777 RFTBWZUQQ5OWKUJA" },
  { "txt-book",
    { "ta:my-notes", "fp:1122334455667788", 0 }, 2,
    0u, 987u, 0.5, 1754870401u,
    "COVEY", "0a1b2c3d", "vector-passcode-a",
    "1|ta:my-notes,fp:1122334455667788|0|987|0.500000|1754870401|COVEY|0a1b2c3d",
    "LHJ6EGNW6D7ICZJN",
    "1|ta:my-notes|0|987|0.499992|1754870401|COVEY|0a1b2c3d",
    "ta:my-notes", "COVEY",
    0u, 987u, 32767u,
    "CBS1 AEAAAAAAAPNWRGJSQF776BKDJ5LEKWILORQTU3LZFVXG65DFOMFBWLB5 HHVJWGKPLLDJCI4W" },
  { "frac-third",
    { "id:x", "fp:0000000000000000", 0 }, 2,
    3u, 100u, 0.3333333333333333, 1754870402u,
    "COVEY", "11223344", "vector-passcode-a",
    "1|id:x,fp:0000000000000000|3|100|0.333333|1754870402|COVEY|11223344",
    "PYBI5LUDWDWHRSRL",
    "1|id:x|3|100|0.333318|1754870402|COVEY|11223344",
    "id:x", "COVEY",
    3u, 100u, 21844u,
    "CBS1 AEAAGAAAABSGRGJSQJKVIBKDJ5LEKWIENFSDU6AREIZUI NDYU3VU6AITHJOKW" },
  { "frac-tiny",
    { "id:y", "fp:1111111111111111", 0 }, 2,
    0u, 1u, 1.52590219e-05, 1754870403u,
    "COVEY", "55667788", "vector-passcode-a",
    "1|id:y,fp:1111111111111111|0|1|0.000015|1754870403|COVEY|55667788",
    "MAGYD6CR3J2T5A4R",
    "1|id:y|0|1|0.000000|1754870403|COVEY|55667788",
    "id:y", "COVEY",
    0u, 1u, 0u,
    "CBS1 AEAAAAAAAAAWRGJSQMAAABKDJ5LEKWIENFSDU6KVMZ3YQ DWSGSTG6MDX4JDGG" },
  { "frac-near-one",
    { "id:z", "fp:2222222222222222", 0 }, 2,
    99u, 65535u, 0.9999847412, 1754870404u,
    "COVEY", "99aabbcc", "vector-passcode-a",
    "1|id:z,fp:2222222222222222|99|65535|0.999985|1754870404|COVEY|99aabbcc",
    "HSYOPQRDI7V7B2D3",
    "1|id:z|99|65535|0.999985|1754870404|COVEY|99aabbcc",
    "id:z", "COVEY",
    99u, 65535u, 65534u,
    "CBS1 AEAGGAAA777WRGJSQT774BKDJ5LEKWIENFSDU6UZVK54Y YJUN5LQZBRVOSWXG" },
  { "long-id",
    { "ta:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "fp:3333333333333333", 0 }, 2,
    1u, 2u, 0.25, 1754870405u,
    "COVEY", "0badc0de", "vector-passcode-a",
    "1|ta:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,fp:3333333333333333|1|2|0.250000|1754870405|COVEY|0badc0de",
    "YZD3LUB37NIVMUWI",
    "1|ta:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|1|2|0.249989|1754870405|COVEY|0badc0de",
    "ta:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "COVEY",
    1u, 2u, 16383u,
    "CBS1 AEAACAAAAABGRGJSQU776BKDJ5LEKWJIORQTUYLBMFQWCYLBMFQWCYLBMFQWCYLBMFQWCYLBMFQWCYLBMFQWCYLBMFQWCYLBBOW4BXQ VKF5K4Z2N5VAJAAB" },
  { "long-dev",
    { "id:dev-trunc", "fp:4444444444444444", 0 }, 2,
    1u, 2u, 0.75, 1754870406u,
    "AVeryLongDeviceNm", "cafebabe", "vector-passcode-a",
    "1|id:dev-trunc,fp:4444444444444444|1|2|0.750000|1754870406|AVeryLongDeviceN|cafebabe",
    "MRKNC4JR6FHTD66Z",
    "1|id:dev-trunc|1|2|0.749996|1754870406|AVeryLongDev|cafebabe",
    "id:dev-trunc", "AVeryLongDev",
    1u, 2u, 49151u,
    "CBS1 AEAACAAAAABGRGJSQ2776DCBKZSXE6KMN5XGORDFOYGGSZB2MRSXMLLUOJ2W4Y6K725L4 BJWREJ6KCUWLN6VE" },
  { "utf8-dev",
    { "id:utf8", "fp:5555555555555555", 0 }, 2,
    5u, 6u, 0.5, 1754870407u,
    "\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""", "feedface", "vector-passcode-a",
    "1|id:utf8,fp:5555555555555555|5|6|0.500000|1754870407|\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""|feedface",
    "JES3BT3XMTHHGU2B",
    "1|id:utf8|5|6|0.499992|1754870407|\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""|feedface",
    "id:utf8", "\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""\xc3""\xa9""",
    5u, 6u, 32767u,
    "CBS1 AEAAKAAAAADGRGJSQ5776DGDVHB2TQ5JYOU4HKODVEDWSZB2OV2GMOH65X5M4 LZMEY7RKBPH2LSXS" },
  { "clamp-spine",
    { "id:clamp", "fp:6666666666666666", 0 }, 2,
    70000u, 5u, 0.125, 1754870408u,
    "COVEY", "12345678", "vector-passcode-a",
    "1|id:clamp,fp:6666666666666666|70000|5|0.125000|1754870408|COVEY|12345678",
    "FJSOKTU6AOEPMBL2",
    "1|id:clamp|65535|5|0.124987|1754870408|COVEY|12345678",
    "id:clamp", "COVEY",
    65535u, 5u, 8191u,
    "CBS1 AH776AAAAACWRGJSRAP76BKDJ5LEKWIINFSDUY3MMFWXAERUKZ4A EMTBEPM2R4LBJNGN" },
  { "frac-over-one",
    { "id:over", "fp:7777777777777777", 0 }, 2,
    2u, 3u, 1.5, 1754870410u,
    "COVEY", "aabbccdd", "vector-passcode-a",
    "1|id:over,fp:7777777777777777|2|3|1.500000|1754870410|COVEY|aabbccdd",
    "V5K33GJU6LUXU3VL",
    "1|id:over|2|3|1.000000|1754870410|COVEY|aabbccdd",
    "id:over", "COVEY",
    2u, 3u, 65535u,
    "CBS1 AEAAEAAAAABWRGJSRL776BKDJ5LEKWIHNFSDU33WMVZKVO6M3U 3746OJBLE5T6ZI3U" },
  { "frac-negative",
    { "id:under", "fp:8888888888888888", 0 }, 2,
    2u, 3u, -0.25, 1754870411u,
    "COVEY", "eeff0011", "vector-passcode-a",
    "1|id:under,fp:8888888888888888|2|3|-0.250000|1754870411|COVEY|eeff0011",
    "4G63BCFM75FEAXMO",
    "1|id:under|2|3|0.000000|1754870411|COVEY|eeff0011",
    "id:under", "COVEY",
    2u, 3u, 0u,
    "CBS1 AEAAEAAAAABWRGJSRMAAABKDJ5LEKWIINFSDU5LOMRSXF3X7AAIQ JIVFY6L6DOBC7P63" },
};
static const int BS_REC_VEC_N = 13;

typedef struct { const char* label; const char* text; const char* passcode; } BsBadVec;
static const BsBadVec BS_BAD_VECS[] = {
  { "wrong-passcode", "CBS1 AEAASAAAAAFGRGJSRF776BKDJ5LEKWIMNFSDU4TFNJSWG5BNNVS2DMWD2Q LM5ASZVSNFYTQILB", "vector-passcode-b" },
  { "tampered-mac", "CBS1 AEAASAAAAAFGRGJSRF776BKDJ5LEKWIMNFSDU4TFNJSWG5BNNVS2DMWD2Q LM5ASZVSBFYTQILB", "vector-passcode-a" },
  { "tampered-payload", "CBS1 AEAASAAAAAFGRGJSRF776BKDJ5LEKBIMNFSDU4TFNJSWG5BNNVS2DMWD2Q LM5ASZVSNFYTQILB", "vector-passcode-a" },
  { "truncated", "CBS1 AEAASAAAAAFGRGJSRF776BKDJ5LEKWIMNFSDU4TFNJSWG5BNNVS2DMWD2Q", "vector-passcode-a" },
  { "no-prefix", "AEAASAAAAAFGRGJSRF776BKDJ5LEKWIMNFSDU4TFNJSWG5BNNVS2DMWD2Q LM5ASZVSNFYTQILB", "vector-passcode-a" },
  { "wrong-prefix", "CBS2 AEAASAAAAAFGRGJSRF776BKDJ5LEKWIMNFSDU4TFNJSWG5BNNVS2DMWD2Q LM5ASZVSNFYTQILB", "vector-passcode-a" },
  { "empty", "", "vector-passcode-a" },
  { "prefix-only", "CBS1 ", "vector-passcode-a" },
  { "non-b32", "CBS1 payload! LM5ASZVSNFYTQILB", "vector-passcode-a" },
  { "garbage", "hello world this is a chat message", "vector-passcode-a" },
};
static const int BS_BAD_VEC_N = 10;

static const char* const BS_IS_SYNC[] = {
  "CBS1 AEAASAAAAAFGRGJSRF776BKDJ5LEKWIMNFSDU4TFNJSWG5BNNVS2DMWD2Q LM5ASZVSNFYTQILB",
  "CBS1 anything at all",
  "CBS1 ",
};
static const int BS_IS_SYNC_N = 3;
static const char* const BS_NOT_SYNC[] = {
  "CBS1",
  "hello",
  "",
  "cbs1 lower case",
  " CBS1 leading space",
  "CBS12 x y",
};
static const int BS_NOT_SYNC_N = 6;

