/* GENERATED by tools/gen_smsmirror_vectors.py — do not edit.
 *
 * Produced by running COVEY's own covey_ui/smsmirror.py, so these are the
 * bytes the radio and the LAN socket will actually carry. Regenerate after
 * ANY change to the format on either side.
 *
 * source: smsmirror.py
 */
#ifndef VECTORS_SMSMIRROR_H
#define VECTORS_SMSMIRROR_H

struct SmVec {
  const char* label;
  const char* line;      // exactly what COVEY puts on the wire
  long long   id;
  const char* peer;      // normalised digits
  bool        out;
  unsigned long ts;
  const char* text;      // what the phone must recover
};

static const SmVec SM_VECS[] = {
  { "plain_in", "CSM1 884451201 4257604281 i 68a1b2c3 on my way, be there in ten", 884451201LL, "4257604281", false, 1755427523UL, "on my way, be there in ten" },
  { "plain_out", "CSM1 884451202 4257604281 o 68a1b2d0 ok see you then", 884451202LL, "4257604281", true, 1755427536UL, "ok see you then" },
  { "spaces", "CSM1 884451203 4257604281 o 68a1b2d1 sure  -  see you at 5 (bring the  map)", 884451203LL, "4257604281", true, 1755427537UL, "sure  -  see you at 5 (bring the  map)" },
  { "leading_space", "CSM1 884451204 4257604281 o 68a1b2d2  leading space matters", 884451204LL, "4257604281", true, 1755427538UL, " leading space matters" },
  { "empty_text", "CSM1 884451205 4257604281 i 68a1b2d3 ", 884451205LL, "4257604281", false, 1755427539UL, "" },
  { "looks_nested", "CSM1 884451206 4257604281 i 68a1b2d4 CSM1 99 5551234567 o 1 gotcha", 884451206LL, "4257604281", false, 1755427540UL, "CSM1 99 5551234567 o 1 gotcha" },
  { "multiline", "CSM1 884451207 4257604281 i 68a1b2d5 line one\\nline two\\r\\nline three", 884451207LL, "4257604281", false, 1755427541UL, "line one\nline two\r\nline three" },
  { "backslash", "CSM1 884451208 4257604281 o 68a1b2d6 C:\\\\path\\\\n not a newline", 884451208LL, "4257604281", true, 1755427542UL, "C:\\path\\n not a newline" },
  { "unicode", "CSM1 884451209 4257604281 i 68a1b2d7 cafe\xcc\x81 \xe2\x80\x94 na\xc3\xafve resume\xcc\x81", 884451209LL, "4257604281", false, 1755427543UL, "cafe\xcc\x81 \xe2\x80\x94 na\xc3\xafve resume\xcc\x81" },
  { "max_len", "CSM1 2147483647 4257604281 i ffffffff WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", 2147483647LL, "4257604281", false, 4294967295UL, "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" },
  { "peer_e164", "CSM1 884451210 4257604281 o 68a1b2d8 typed with a country code", 884451210LL, "4257604281", true, 1755427544UL, "typed with a country code" },
  { "peer_pretty", "CSM1 884451211 4257604281 o 68a1b2d9 typed by a human", 884451211LL, "4257604281", true, 1755427545UL, "typed by a human" },
  { "peer_sipuri", "CSM1 884451212 4257604281 i 68a1b2da off the wire", 884451212LL, "4257604281", false, 1755427546UL, "off the wire" },
};
static const int SM_VEC_N = 13;

#endif // VECTORS_SMSMIRROR_H
