// GENERATED by tools/gen_kosync_vectors.py - do not edit. See that file for the rules.
#pragma once
#include <stdint.h>
typedef struct { const char* in; const char* hex; } KsMd5Vec;
static const KsMd5Vec KS_MD5[] = {
  { "", "d41d8cd98f00b204e9800998ecf8427e" },
  { "a", "0cc175b9c0f1b6a831c399e269772661" },
  { "abc", "900150983cd24fb0d6963f7d28e17f72" },
  { "message digest", "f96b697d7cb7938d525a2f31aaf161d0" },
  { "abcdefghijklmnopqrstuvwxyz", "c3fcd3d76192e4007dfb496cca67e13b" },
  { "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", "d174ab98d277d9f5a5611c2c9f419d9f" },
  { "12345678901234567890123456789012345678901234567890123456789012345678901234567890", "57edf4a22be3c955ac49da2e2107b67a" },
};
typedef struct { double p; const char* text; } KsFmtVec;
static const KsFmtVec KS_FMT[] = {
  { 0, "0" },
  { 1, "1" },
  { 0.5, "0.5" },
  { 0.23100000000000001, "0.231" },
  { 0.1234565, "0.123456" },
  { 0.99999959999999999, "1" },
  { 9.9999999999999995e-07, "0.000001" },
  { 3.9999999999999998e-07, "0" },
  { 0.25, "0.25" },
};
typedef struct { const char* body; int has; double pct; const char* device; long long ts; } KsParseVec;
static const KsParseVec KS_PARSE[] = {
  { "{\"document\":\"d41d8cd98f00b204e9800998ecf8427e\",\"percentage\":0.5,\"progress\":\"\",\"device\":\"COVEY\",\"device_id\":\"covey-1\",\"timestamp\":1790000000}", 1, 0.5, "COVEY", 1790000000LL },
  { "{\"timestamp\":1790000001,\"device_id\":\"crosspoint-reader\",\"progress\":\"/body/DocFragment[8]/body\",\"percentage\":0.231,\"device\":\"CrossPoint\",\"document\":\"x\"}", 1, 0.23100000000000001, "CrossPoint", 1790000001LL },
  { "{\"percentage\": 6.0E-4, \"device\": \"KOReader\", \"progress\": \"12\", \"timestamp\": 5}", 1, 0.00059999999999999995, "KOReader", 5LL },
  { "{\"percentage\":1,\"device\":\"WiPhone-NICK\",\"timestamp\":7}", 1, 1, "WiPhone-NICK", 7LL },
  { "{}", 0, 0, "", 0 },
};
typedef struct { const char* path; uint32_t size; } KsCpItem;
typedef struct { int r; double within; double pct; } KsFwd;
typedef struct { double p; int cp; double within; int r; double rwithin; } KsInv;
typedef struct {
  const char* file; uint32_t size; const char* partialMd5; const char* filenameMd5;
  const KsCpItem* cp; int nCp; const uint32_t* cum; uint32_t total;
  const char* const* reading; int nReading; const int* readingToCp;
  const KsFwd* fwd; int nFwd; const KsInv* inv; int nInv;
} KsBook;
static const KsCpItem KS_B0_CP[] = {
  { "OEBPS/Text/cover.xhtml", 162u },
  { "OEBPS/Text/front.xhtml", 40u },
  { "OEBPS/Images/map.jpg", 200002u },
  { "OEBPS/Text/one.xhtml", 2703u },
  { "OEBPS/Text/chapter 2.xhtml", 5234u },
  { "OEBPS/Text/missing.xhtml", 0u },
  { "OEBPS/Text/three.xhtml", 85351u },
  { "OEBPS/Text/four.xhtml", 834u },
};
static const uint32_t KS_B0_CUM[] = { 162u, 202u, 200204u, 202907u, 208141u, 208141u, 293492u, 294326u };
static const char* const KS_B0_RD[] = { "OEBPS/Text/front.xhtml", "OEBPS/Text/one.xhtml", "OEBPS/Text/three.xhtml", "OEBPS/Text/four.xhtml" };
static const int KS_B0_R2C[] = { 1, 3, 6, 7 };
static const KsFwd KS_B0_FWD[] = {
  { 0, 0, 0.00055041008949260342 },
  { 0, 0.25, 0.00058438602094276412 },
  { 0, 0.5, 0.00061836195239292483 },
  { 0, 0.999, 0.00068617791156744561 },
  { 1, 0, 0.68021173800479739 },
  { 1, 0.25, 0.68250766157254206 },
  { 1, 0.5, 0.68480358514028661 },
  { 1, 0.999, 0.68938624858150488 },
  { 2, 0, 0.70717843479678999 },
  { 2, 0.25, 0.77967542792685662 },
  { 2, 0.5, 0.85217242105692326 },
  { 2, 0.999, 0.9968764193445363 },
  { 3, 0, 0.99716640731705664 },
  { 3, 0.25, 0.99787480548779239 },
  { 3, 0.5, 0.99858320365852826 },
  { 3, 0.999, 0.99999716640731717 },
};
static const KsInv KS_B0_INV[] = {
  { 0, 0, 0, 0, 0 },
  { 9.9999999999999995e-07, 0, 0.001816827160493827, 0, 0 },
  { 0.5, 2, 0.7347976520234798, 1, 0 },
  { 1, 7, 1, 3, 1 },
  { 0.00055041008949260342, 0, 1, 0, 0 },
  { 0.00054701249634758742, 0, 0.99382716049382736, 0, 0 },
  { 0.00055380768263761952, 1, 0.025000000000000001, 0, 0.025000000000000001 },
  { 0.00068631381529324624, 1, 1, 0, 1 },
  { 0.00068291622214823014, 1, 0.97499999999999931, 0, 0.97499999999999931 },
  { 0.00068971140843826235, 2, 4.9999500004999954e-06, 1, 0 },
  { 0.68021173800479739, 2, 1, 1, 0 },
  { 0.68020834041165235, 2, 0.99999500004999953, 1, 0 },
  { 0.68021513559794244, 3, 0.00036995930447650759, 1, 0.00036995930447650759 },
  { 0.68939543227577582, 3, 1, 1, 1 },
  { 0.68939203468263077, 3, 0.99963004069551276, 1, 0.99963004069551276 },
  { 0.68939882986892087, 4, 0.00019105846388995032, 2, 0 },
  { 0.70717843479678999, 4, 1, 2, 0 },
  { 0.70717503720364494, 4, 0.99980894153611, 2, 0 },
  { 0.70718183238993493, 6, 1.1716324354723436e-05, 2, 1.1716324354723436e-05 },
  { 0.99716640731705664, 6, 1, 2, 1 },
  { 0.99716300972391159, 6, 0.9999882836756453, 2, 0.9999882836756453 },
  { 0.99716980491020157, 7, 0.001199040767386091, 3, 0.001199040767386091 },
  { 0.99999660240685495, 7, 0.99880095923261392, 3, 0.99880095923261392 },
};
static const KsCpItem KS_B1_CP[] = {
  { "a.xhtml", 489u },
  { "b.xhtml", 3568u },
  { "c.xhtml", 1265u },
};
static const uint32_t KS_B1_CUM[] = { 489u, 4057u, 5322u };
static const char* const KS_B1_RD[] = { "a.xhtml", "b.xhtml", "c.xhtml" };
static const int KS_B1_R2C[] = { 0, 1, 2 };
static const KsFwd KS_B1_FWD[] = {
  { 0, 0, 0 },
  { 0, 0.25, 0.022970687711386696 },
  { 0, 0.5, 0.045941375422773392 },
  { 0, 0.999, 0.091790868094701245 },
  { 1, 0, 0.091882750845546785 },
  { 1, 0.25, 0.25948891394212703 },
  { 1, 0.5, 0.42709507703870725 },
  { 1, 0.999, 0.76163697857948132 },
  { 2, 0, 0.76230740323186774 },
  { 2, 0.25, 0.82173055242390081 },
  { 2, 0.5, 0.88115370161593387 },
  { 2, 0.999, 0.9997623074032318 },
};
static const KsInv KS_B1_INV[] = {
  { 0, 0, 0, 0, 0 },
  { 9.9999999999999995e-07, 0, 1.0883435582822084e-05, 0, 1.0883435582822084e-05 },
  { 0.5, 1, 0.60874439461883412, 1, 0.60874439461883412 },
  { 1, 2, 1, 2, 1 },
  { 0.091882750845546785, 0, 1, 0, 1 },
  { 0.09169485155956407, 0, 0.99795501022494892, 0, 0.99795501022494892 },
  { 0.0920706501315295, 1, 0.00028026905829596412, 1, 0.00028026905829596412 },
  { 0.76230740323186774, 1, 1, 1, 1 },
  { 0.76211950394588501, 1, 0.99971973094170408, 1, 0.99971973094170408 },
  { 0.76249530251785047, 2, 0.00079051383399209485, 2, 0.00079051383399209485 },
  { 0.99981210071401727, 2, 0.99920948616600791, 2, 0.99920948616600791 },
};
static const KsCpItem KS_B2_CP[] = {
  { "ch1.xhtml", 303u },
  { "ch2.xhtml", 296u },
  { "cover.jpg", 21u },
};
static const uint32_t KS_B2_CUM[] = { 303u, 599u, 620u };
static const char* const KS_B2_RD[] = { "ch1.xhtml", "ch2.xhtml" };
static const int KS_B2_R2C[] = { 0, 1 };
static const KsFwd KS_B2_FWD[] = {
  { 0, 0, 0 },
  { 0, 0.25, 0.12217741935483871 },
  { 0, 0.5, 0.24435483870967742 },
  { 0, 0.999, 0.48822096774193546 },
  { 1, 0, 0.48870967741935484 },
  { 1, 0.25, 0.60806451612903223 },
  { 1, 0.5, 0.72741935483870968 },
  { 1, 0.999, 0.96565161290322576 },
};
static const KsInv KS_B2_INV[] = {
  { 0, 0, 0, 0, 0 },
  { 9.9999999999999995e-07, 0, 2.0462046204620461e-06, 0, 2.0462046204620461e-06 },
  { 0.5, 1, 0.02364864864864865, 1, 0.02364864864864865 },
  { 1, 2, 1, 1, 1 },
  { 0.48870967741935484, 0, 1, 0, 1 },
  { 0.48709677419354841, 0, 0.99669966996699666, 0, 0.99669966996699666 },
  { 0.49032258064516127, 1, 0.0033783783783783786, 1, 0.0033783783783783786 },
  { 0.96612903225806457, 1, 1, 1, 1 },
  { 0.96451612903225803, 1, 0.9966216216216216, 1, 0.9966216216216216 },
  { 0.967741935483871, 2, 0.047619047619047616, 1, 1 },
  { 0.99838709677419357, 2, 0.95238095238095233, 1, 1 },
};
static const KsCpItem KS_B3_CP[] = {
  { "OEBPS/text/one.xhtml", 273u },
  { "OEBPS/text/two.xhtml", 246u },
};
static const uint32_t KS_B3_CUM[] = { 273u, 519u };
static const char* const KS_B3_RD[] = { "OEBPS/text/one.xhtml", "OEBPS/text/two.xhtml" };
static const int KS_B3_R2C[] = { 0, 1 };
static const KsFwd KS_B3_FWD[] = {
  { 0, 0, 0 },
  { 0, 0.25, 0.13150289017341041 },
  { 0, 0.5, 0.26300578034682082 },
  { 0, 0.999, 0.52548554913294798 },
  { 1, 0, 0.52601156069364163 },
  { 1, 0.25, 0.6445086705202312 },
  { 1, 0.5, 0.76300578034682076 },
  { 1, 0.999, 0.99952601156069365 },
};
static const KsInv KS_B3_INV[] = {
  { 0, 0, 0, 0, 0 },
  { 9.9999999999999995e-07, 0, 1.9010989010989009e-06, 0, 1.9010989010989009e-06 },
  { 0.5, 0, 0.9505494505494505, 0, 0.9505494505494505 },
  { 1, 1, 1, 1, 1 },
  { 0.52601156069364163, 0, 1, 0, 1 },
  { 0.52408477842003853, 0, 0.99633699633699635, 0, 0.99633699633699635 },
  { 0.52793834296724473, 1, 0.0040650406504065045, 1, 0.0040650406504065045 },
  { 0.9980732177263969, 1, 0.99593495934959353, 1, 0.99593495934959353 },
};
static const KsBook KS_BOOKS[] = {
  { "kosync-mixed.epub", 289356u, "7db24c08211c49e8e0c2b8522e9efc1b", "ad7a1fcd11740eb658e5cd1742a8bfed", KS_B0_CP, 8, KS_B0_CUM, 294326u, KS_B0_RD, 4, KS_B0_R2C,
    KS_B0_FWD, 16, KS_B0_INV, 23 },
  { "kosync-plain.epub", 2482u, "d1d6d400f5a32bfd6a3534f2a71c0ded", "1effecd36ed99dc7d6946de29315914e", KS_B1_CP, 3, KS_B1_CUM, 5322u, KS_B1_RD, 3, KS_B1_R2C,
    KS_B1_FWD, 12, KS_B1_INV, 11 },
  { "epub3-nav.epub", 1801u, "81af28fa9ff5c73943eaa228d3d49f2d", "65265deae64e922ed12a15387f9c290c", KS_B2_CP, 3, KS_B2_CUM, 620u, KS_B2_RD, 2, KS_B2_R2C,
    KS_B2_FWD, 8, KS_B2_INV, 11 },
  { "epub2-subdir.epub", 1725u, "fdf60b0fd2c872e18fe30bda0ebc37f4", "26b6a438bd8440f7477970bd4cd59d22", KS_B3_CP, 2, KS_B3_CUM, 519u, KS_B3_RD, 2, KS_B3_R2C,
    KS_B3_FWD, 8, KS_B3_INV, 8 },
};
typedef struct { const char* file; uint32_t size; const char* partialMd5; const char* filenameMd5; } KsTxt;
static const KsTxt KS_TXT[] = {
  { "my-notes.txt", 54u, "e64ddde6fef1ee23f9e0af3c5a547d48", "65850887df540401b94816c45d5c2a9f" },
};
