/* GENERATED by tools/gen_replay_vectors.py — DO NOT EDIT.
 *
 * Frozen behavior of COVEY's covey_ui/replay.py (the reference
 * implementation of docs/replay-spec.md). test_replay.cpp proves
 * replay_proto.cpp agrees byte-for-byte; a failure here means the
 * two devices would disagree on the wire.
 * PACKET_BUDGET=180
 */
#ifndef VECTORS_REPLAY_H
#define VECTORS_REPLAY_H

typedef struct { const char* text; int valid; unsigned t1, t2; int maxn; } RplReqVec;
static const RplReqVec RPL_REQ_VEC[] = {
  { "RPL? 100 200 40", 1, 100u, 200u, 40 },
  { "RPL? 0 0 1", 1, 0u, 0u, 1 },
  { "RPL? 1755791000 1755795000 40", 1, 1755791000u, 1755795000u, 40 },
  { "RPL? 4294967295 4294967295 999", 1, 4294967295u, 4294967295u, 999 },
  { "RPL?  100  200  40", 1, 100u, 200u, 40 },
  { "RPL? 100\t200 40", 1, 100u, 200u, 40 },
  { "RPL? 100 200 40 ", 1, 100u, 200u, 40 },
  { "RPL? 200 100 40", 0, 0u, 0u, 0 },
  { "RPL? 100 200 0", 0, 0u, 0u, 0 },
  { "RPL? +5 200 40", 0, 0u, 0u, 0 },
  { "RPL? -5 200 40", 0, 0u, 0u, 0 },
  { "RPL? 100 200", 0, 0u, 0u, 0 },
  { "RPL? 100 200 40 7", 0, 0u, 0u, 0 },
  { "RPL? 4294967296 4294967297 1", 0, 0u, 0u, 0 },
  { "RPL? a b c", 0, 0u, 0u, 0 },
  { "RPL 100 aabbccdd ch x", 0, 0u, 0u, 0 },
  { "RPL?100 200 40", 0, 0u, 0u, 0 },
};
static const int RPL_REQ_VEC_N = 17;

typedef struct { unsigned ts, sender; const char* chan; const char* text; const char* line; } RplRecVec;
static const RplRecVec RPL_REC_VEC[] = {
  { 1755791640u, 0x62B8D2FDu, "Howe group", "Testing hello", "RPL 1755791640 62b8d2fd Howe%20group Testing hello" },
  { 5u, 0x1EC2BCA2u, "a%b c", "x % y ~ z", "RPL 5 1ec2bca2 a%25b%20c x % y ~ z" },
  { 7u, 0xAABBCCDDu, "ch", "line\nbreak\rgone", "RPL 7 aabbccdd ch line break gone" },
  { 0u, 0x00000001u, "LongFast", "clockless zero is a legal ts", "RPL 0 00000001 LongFast clockless zero is a legal ts" },
  { 1700000000u, 0x43588D68u, "booksync", "deer spotted \xf0" "\x9f" "\xa6" "\x8c at 40yd", "RPL 1700000000 43588d68 booksync deer spotted \xf0" "\x9f" "\xa6" "\x8c at 40yd" },
  { 1700000001u, 0xFFFFFFFFu, "x", "", "RPL 1700000001 ffffffff x " },
};
static const int RPL_REC_VEC_N = 6;

typedef struct { int sent, gap; const char* text; } RplSumVec;
static const RplSumVec RPL_SUM_VEC[] = {
  { 0, 0, "RPL. 0 0" },
  { 12, 1, "RPL. 12 1" },
  { 40, 0, "RPL. 40 0" },
};
static const int RPL_SUM_VEC_N = 3;

static const char* const RPL_IS_REPLAY[] = {
  "RPL? 1 2 3",
  "RPL 1 aabbccdd ch x",
  "RPL. 1 0",
  "RPL",
  "RPL2 future",
};
static const int RPL_IS_REPLAY_N = 5;
static const char* const RPL_NOT_REPLAY[] = {
  "really? cool",
  "CBS1 abc def",
  "rpl lowercase is chat",
  " RPL leading space",
};
static const int RPL_NOT_REPLAY_N = 4;

#endif // VECTORS_REPLAY_H
