/*
 * booksync.h — COVEY-compatible reading-position sync. WiPhone side of the wire protocol.
 *
 * The protocol is COVEY's, specified in its firmware/pi/covey-ui/covey_ui/booksync.py and in
 * decision D-089 of the COVEY doc package. This is a port, not a redesign: nothing here is
 * free to change, because the two devices only agree if the bytes agree.
 *
 * ══════════════════════════════════════════════════════════════════════════════════
 * THE ONE THING THAT MAKES THIS HARD TO DEBUG
 * ══════════════════════════════════════════════════════════════════════════════════
 *
 * A packet signed with the wrong passcode and a packet signed by a wrong IMPLEMENTATION are
 * indistinguishable: both are dropped in silence, with nothing logged and nothing sent back.
 * That silence is deliberate on COVEY's side — telling an unauthenticated peer why it failed
 * is how you build an oracle — but it means a one-byte mistake in here presents as "sync
 * just doesn't work", with no clue on either device.
 *
 * So this file is not trusted until tests/test_booksync.cpp passes. Those vectors are
 * GENERATED by running COVEY's actual booksync.py (tools/gen_booksync_vectors.py), so they
 * are ground truth, not a second reading of the spec.
 *
 * ══════════════════════════════════════════════════════════════════════════════════
 * THE WIRE FORM
 * ══════════════════════════════════════════════════════════════════════════════════
 *
 *   text     "CBS1 <base32 payload> <base32 mac>"     (~77-136 chars; the mesh limit is 234)
 *   key      SHA-256("covey-booksync-v1" + passcode)
 *   mac      HMAC-SHA256(key, canonical), first 10 bytes, base32, no padding
 *   canon    "v|ids,joined|spine|offset|fraction(6dp)|turnedAt|device|nonce"
 *
 * ⚠ THE TRAP, which cost COVEY a debugging session and is called out in D-089: for a mesh
 * packet the mac is computed over the REDUCED record (bookSyncReduceForMesh), NOT over the
 * full one. A receiver can only rebuild the reduced form — first id only, device name cut to
 * 12 BYTES, fraction quantised to 1/65535ths — so signing the original makes every single
 * packet fail to verify while pack/unpack of the fields looks perfectly correct.
 *
 * ══════════════════════════════════════════════════════════════════════════════════
 * MATCHING BOOKS
 * ══════════════════════════════════════════════════════════════════════════════════
 *
 * Books are matched by epub ids, never by filename: "id:<dc:identifier>", "ta:<title|author>",
 * "fp:<content fingerprint>", best first. ANY overlap means "same book". A mesh packet only
 * carries the FIRST id (airtime is the budget), so the two devices must derive the same first
 * id for the same book — which is why byte-identical copies of a file are the happy path.
 */
#ifndef BOOKSYNC_H
#define BOOKSYNC_H

#include <stddef.h>
#include <stdint.h>

#define BOOKSYNC_VERSION        1
#define BOOKSYNC_MAC_LEN        10        // bytes of HMAC kept -> 16 base32 chars
#define BOOKSYNC_MAC_CHARS      16
#define BOOKSYNC_KDF_SALT       "covey-booksync-v1"
#define BOOKSYNC_MESH_PREFIX    "CBS1"

#define BOOKSYNC_MAX_IDS        3
#define BOOKSYNC_ID_MAX         72        // "ta:" + a 64-char slug + NUL, with slack
#define BOOKSYNC_DEV_MAX        72        // 16 characters, which is up to 64 UTF-8 bytes
#define BOOKSYNC_NONCE_CHARS    8

#define BOOKSYNC_MESH_ID_BYTES  40        // reduce_for_mesh: first id cut to this many BYTES
#define BOOKSYNC_MESH_DEV_BYTES 12        // reduce_for_mesh: device name cut to this
#define BOOKSYNC_MESH_TEXT_MAX  192       // longest packet we will ever build, plus slack
#define BOOKSYNC_CANON_MAX      512

struct BookSyncRecord {
  uint8_t  version;
  char     ids[BOOKSYNC_MAX_IDS][BOOKSYNC_ID_MAX];
  uint8_t  nIds;
  uint32_t spine;
  uint32_t offset;
  double   fraction;                      // 0.0 - 1.0 through the whole book
  uint32_t turnedAt;                      // unix time of the LAST PAGE TURN, not of sending
  char     dev[BOOKSYNC_DEV_MAX];
  char     nonce[BOOKSYNC_NONCE_CHARS + 1];
};

// key = SHA-256(KDF_SALT + passcode). A NULL or empty passcode is legal and still derives a
// key — it is simply a well-known one, exactly as on COVEY.
void bookSyncDeriveKey(const char* passcode, uint8_t key[32]);

/* Fill a record. `device` is truncated to 16 CHARACTERS (not bytes) and `nonce` must be 8
 * hex characters — pass NULL to have one generated from `randomSeedFn`. */
void bookSyncMakeRecord(BookSyncRecord* r,
                        const char* const* ids, int nIds,
                        uint32_t spine, uint32_t offset, double fraction,
                        uint32_t turnedAt, const char* device, const char* nonce);

// The exact string that gets signed. Returns the length, or 0 if it would not fit.
size_t bookSyncCanonical(const BookSyncRecord* r, char* out, size_t cap);

// base32 mac of `r` under `key`. `out` needs BOOKSYNC_MAC_CHARS + 1 bytes.
bool bookSyncSign(const BookSyncRecord* r, const uint8_t key[32], char* out);

// The lossy record a mesh packet actually carries. See the trap note above.
void bookSyncReduceForMesh(const BookSyncRecord* in, BookSyncRecord* out, uint16_t* frQOut);

// Build "CBS1 <payload> <mac>". `out` needs BOOKSYNC_MESH_TEXT_MAX bytes.
bool bookSyncPackMesh(const BookSyncRecord* r, const uint8_t key[32], char* out, size_t cap);

// Parse and VERIFY a "CBS1 ..." message. False for anything malformed or wrongly signed.
bool bookSyncUnpackMesh(const char* text, const uint8_t key[32], BookSyncRecord* out);

/* True for a message that is machine traffic rather than something to show in Chats.
 *
 * Checked BEFORE the mac, and deliberately: a packet signed with someone else's passcode is
 * still not a chat message, and dumping "CBS1 MFRGG..." into the message list would be worse
 * than dropping it. */
bool bookSyncIsSyncText(const char* text);

// ANY overlap means "same book" — the whole matching rule.
bool bookSyncIdsMatch(const char* const* a, int na, const char* const* b, int nb);
bool bookSyncRecordMatchesIds(const BookSyncRecord* r, const char* const* ids, int nIds);

// Its last page turn is in the future by more than 5 minutes: that clock is provably wrong.
// COVEY flags this on the confirm card rather than refusing the packet.
bool bookSyncSuspectClock(const BookSyncRecord* r, uint32_t nowUnix);

#endif // BOOKSYNC_H
