/*
 * mesh_wire.h — the Meshtastic on-air wire format: Data protobuf + PacketHeader.
 *
 * This phone speaks Meshtastic without nanopb and without a line of upstream source: the
 * protobufs are hand-rolled as literal tag bytes. That is cheap and small, and it is
 * exactly the kind of code that rots SILENTLY when the other end changes — a wrong field
 * number does not crash, it just makes this phone invisible to every other radio.
 *
 * 🔑 SO THE POINT OF THIS FILE IS THAT IT IS ARDUINO-FREE AND THEREFORE HOST-TESTABLE.
 * tests/test_wire.cpp compiles it with the Mac's compiler and asserts its bytes against
 * vectors generated by the REAL Meshtastic python protobufs (tools/gen_wire_vectors.py,
 * meshtastic 2.7.11). Byte equality against an independent implementation is the only
 * honest check there is; "it parses" proves nothing about what other radios will read.
 * It lived as file-statics inside meshtastic_service.cpp until 2026-09-02, where nothing
 * could reach it — that file pulls in the ESP32 SDK and cannot be built on a host.
 *
 * ⚠ IF YOU CHANGE ANY BYTE IN HERE, REGENERATE THE VECTORS AND RUN THE SUITE. If the
 * generator and the firmware disagree, the firmware is wrong: the generator is upstream's
 * own runtime, and it is what every other node in the mesh uses.
 *
 * Forward compatibility is deliberate and is the reason upstream releases do not break
 * this phone: every parser here walks tag/wire-type pairs and SKIPS fields it does not
 * know, so fields Meshtastic adds later are stepped over rather than choking the decode.
 * Only a change to an EXISTING field's number or meaning can hurt, which is what the
 * vectors are there to catch.
 */

#ifndef MESH_WIRE_H
#define MESH_WIRE_H

#include <stdint.h>
#include <stddef.h>

#include "mesh_packet.h"
#include "mesh_pki.h"     // MESH_PKI_KEY_LEN

/* ── PORTNUMS ────────────────────────────────────────────────────────────────────────
 * The Data.portnum values this phone speaks. They lived in meshtastic_service.cpp, where
 * no test could see them; tests/test_wire.cpp now asserts each one still equals upstream's
 * portnums.proto. A renumbering upstream would route our packets to the wrong app on every
 * other radio and is exactly the kind of drift nothing else here would notice.
 * (NEIGHBORINFO 71 keeps its home in neighbor_info.h, beside the encoder that uses it.) */
#define MESH_PORT_TEXT_MESSAGE  1
#define MESH_PORT_POSITION      3   // COVEY broadcasts one every 5 minutes
#define MESH_PORT_NODEINFO      4
#define MESH_PORT_ROUTING       5   // ACK/NAK carrier: Routing{error_reason}
#define MESH_PORT_WAYPOINT      8   // camp / truck / stand pins from COVEY's map

/* ── PROTOBUF PRIMITIVES ─────────────────────────────────────────────────────────── */

/* Append a length-delimited field (tag + length + bytes). Returns bytes written.
 * ⚠ The length varint is emitted as at most TWO bytes, so `len` must be < 16384. Every
 * caller is bounded by the LoRa payload (~233 B) so this has always held; it is written
 * down because the function itself does not check.
 * ⚠ No bounds check against `out`. Pre-existing and true of every caller here — the
 * buffers are fixed 256-byte stack arrays sized for a payload that cannot exceed 234. */
size_t meshPbBytes(uint8_t* out, int field, const uint8_t* val, size_t len);
size_t meshPbString(uint8_t* out, int field, const char* s);

/* ── ENCODE ──────────────────────────────────────────────────────────────────────── */

/* Serialize a Data protobuf: { portnum, payload, [want_response], [request_id], bitfield }.
 * The bitfield (field 9, added in Meshtastic 2.5) mirrors stock's Router:
 * bit0 = ok-to-MQTT (we say no — private mesh), bit1 = want_response.
 * request_id (field 6, fixed32) is nonzero only on ACK/NAK Routing replies. */
size_t meshBuildData(uint8_t* data, int portnum,
                     const uint8_t* payload, size_t payloadLen,
                     bool wantResponse, uint32_t requestId);

/* Fill the 16-byte unencrypted header that precedes every frame.
 * ⚠ `hopLimit` USED TO BE A FILE STATIC (`s_hopLimit`) read from in here. It is a
 * parameter now because a function that silently reads shared mutable state is the single
 * most productive bug class in this repo — the same shape as the Audio singleton. The
 * caller owns the setting; this only encodes it. */
void meshFillHeader(MeshPacketHeader* hdr, uint32_t sender, uint32_t dest,
                    uint32_t packetId, uint8_t channelHash, uint8_t hopLimit);


/* Serialize a User protobuf — the NODEINFO payload: { id, long_name, short_name,
 * [public_key] }. The id is Meshtastic's "!%08x" of the node number, formatted here so the
 * one place that spelling exists is the one place that is tested.
 * `pubKey` NULL omits field 8. That key is the whole reason 2.5+ nodes will DM us at all:
 * without it every DM from a stock node dies with PKI_SEND_FAIL_PUBLIC_KEY. */
size_t meshBuildUser(uint8_t* out, uint32_t nodeNum, const char* longName,
                     const char* shortName, const uint8_t* pubKey);

/* ── DECODE ──────────────────────────────────────────────────────────────────────── */

/* Parse a decrypted Data protobuf. Returns field 1 (portnum) or -1, and hands back field 2
 * (payload) via the out params. The payload's meaning depends on portnum: UTF-8 text for
 * TEXT_MESSAGE, a nested User protobuf for NODEINFO, etc. Bounds-checked against `dlen`.
 *
 * ⚠ `wantRespOut` is optional and may be NULL. It carries Data field 3, want_response —
 * how every other Meshtastic node asks "tell me who you are". This was previously only ever
 * SET on the send side and never read on receive, so the phone asked the question and never
 * answered it: it appeared on other radios as a bare node number with no name until it
 * happened to announce on its own.
 * `requestIdOut` (optional) carries Data field 6, request_id — on a ROUTING packet it names
 * the packet an ACK/NAK is answering, which is the phone's only proof of DM delivery. */
int meshParseData(const uint8_t* data, size_t dlen,
                  const uint8_t** payloadOut, size_t* payloadLenOut,
                  bool* wantRespOut = NULL, uint32_t* requestIdOut = NULL);

/* Extract a display name from a User protobuf (the NODEINFO payload): prefer long_name
 * (field 2), fall back to short_name (field 3). Returns true if a non-empty name was
 * copied into `out` (null-terminated).
 * `pubKeyOut`/`hasKeyOut` (optional) receive field 8, public_key — the node's X25519 key,
 * ONLY when it is exactly 32 bytes (stock strips it for ham/licensed operators, so absence
 * is normal, not an error). */
bool meshParseUserName(const uint8_t* data, size_t dlen, char* out, size_t outCap,
                       uint8_t* pubKeyOut = NULL, bool* hasKeyOut = NULL);

#endif // MESH_WIRE_H
