/*
 * neighbor_info.h — Meshtastic NeighborInfo (portnum 71) encoding.
 *
 * Nick asked for a neighbor-info toggle on both devices: it is how you build a
 * picture of who-hears-whom while hunting. The RAK has the module built in;
 * this phone speaks the protocol itself, so it has to encode the packet.
 *
 * WHAT ACTUALLY TRAVELS (verified against the 2.7.11 protobufs, mesh_pb2.pyi
 * 4116-4155): a Neighbor's `last_rx_time` and `node_broadcast_interval_secs`
 * are marked "for local storage only and will not be sent out over the mesh",
 * so an on-air Neighbor is node_id + snr and nothing else. Encoding the extra
 * fields would just burn airtime on bytes every receiver discards.
 *
 * DIRECT NEIGHBOURS ONLY, and that is the whole point: a node is a neighbour
 * if we heard it with NO relay in between (hop_start == hop_limit). Listing a
 * node we only ever heard through a repeater would draw an edge on the map
 * that does not exist — worse than no map.
 *
 * Arduino-free so the host suite compiles it (tests/test_neighbor.cpp checks
 * the bytes against vectors generated by the real python protobuf).
 */

#ifndef NEIGHBOR_INFO_H
#define NEIGHBOR_INFO_H

#include <stdint.h>
#include <stddef.h>

#define MESH_PORT_NEIGHBORINFO 71

typedef struct {
  uint32_t nodeNum;
  float    snr;
} NeighborEntry;

/* Encode a NeighborInfo message. Returns bytes written, or -1 if it would not
 * fit `cap`. Neighbours are emitted in the order given; the caller is expected
 * to have sorted them (strongest/most recent first) so that a truncated list
 * keeps the most useful edges. */
int neighborInfoEncode(uint8_t* out, size_t cap,
                       uint32_t myNodeNum, uint32_t intervalSecs,
                       const NeighborEntry* neighbors, int count);

/* How many neighbours fit in `cap` bytes of payload, given the header cost.
 * Used to trim the list before encoding rather than failing at the end. */
int neighborInfoCapacity(size_t cap, uint32_t myNodeNum, uint32_t intervalSecs);

#endif // NEIGHBOR_INFO_H
