#!/usr/bin/env python3
"""Generate WiPhone/html_entities.h from Python's own HTML5 entity table.

COVEY extracts chapter text with HTMLParser(convert_charrefs=True), which decodes every named
HTML entity. A reading position is a CHARACTER OFFSET into that extracted text, so any entity
this parser fails to decode makes the WiPhone's text longer than COVEY's from that point on —
and the error accumulates down the chapter rather than staying local. A hand-picked list of
"common" entities is therefore not good enough; the table has to be the same table.

Generated straight from html.entities.html5 so it cannot drift from what COVEY's parser does.
Only the ';'-terminated forms are kept: the legacy no-semicolon forms (&amp vs &amp;) are
invalid in XHTML and would need longest-match scanning to handle correctly.

Usage: python3 tools/gen_entities.py --out WiPhone/html_entities.h
"""
import argparse
import html.entities


def c_bytes(s):
    return "".join('\\x%02x' % b for b in s.encode("utf-8"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    ents = {}
    for name, ch in html.entities.html5.items():
        if not name.endswith(";"):
            continue
        ents[name[:-1]] = ch

    names = sorted(ents)                      # sorted for binary search by strcmp
    longest = max(len(n) for n in names)
    widest = max(len(ents[n].encode("utf-8")) for n in names)

    L = []
    w = L.append
    w("/* GENERATED by tools/gen_entities.py from Python's html.entities.html5 — do not edit.")
    w(" *")
    w(" * The same table COVEY's HTMLParser decodes with. An entity this misses would make a")
    w(" * chapter's extracted text longer than COVEY's, and since a reading position is a")
    w(" * character offset into that text, the error would grow through the chapter.")
    w(" *")
    w(" * %d entities, longest name %d chars, widest expansion %d bytes." % (len(names), longest, widest))
    w(" */")
    w("#pragma once")
    w("")
    w("#define HTML_ENTITY_MAX_NAME %d" % longest)
    w("")
    w("struct HtmlEntity { const char* name; const char* utf8; };")
    w("")
    w("// Sorted by name (strcmp order) so lookup is a binary search.")
    w("static const HtmlEntity HTML_ENTITIES[] = {")
    for n in names:
        w('  { "%s", "%s" },' % (n, c_bytes(ents[n])))
    w("};")
    w("static const int HTML_ENTITY_N = %d;" % len(names))

    with open(args.out, "w") as f:
        f.write("\n".join(L) + "\n")
    print("wrote %s: %d entities, longest name %d, widest expansion %d bytes"
          % (args.out, len(names), longest, widest))


if __name__ == "__main__":
    main()
