#!/usr/bin/env python3
"""Generate tests/vectors_replay.h from COVEY's covey_ui/replay.py.

The replay wire format (docs/replay-spec.md) has two implementations: COVEY's
replay.py (the reference) and the phone's replay_proto.cpp. This generator runs
the REFERENCE and freezes its behavior into a C header, so the host suite
proves the phone agrees byte-for-byte — requests it must parse (and refuse),
record lines it must emit identically, summaries likewise. A failure here means
the two devices would disagree on the wire.

    python3 tools/gen_replay_vectors.py \
        --replay ../New_phone_project/Project_definition_and_documents/COVEY_RevA_v0.5/firmware/pi/covey-ui/covey_ui/replay.py \
        --out tests/vectors_replay.h
"""
import argparse
import importlib.util
import sys


def load_replay(path):
    spec = importlib.util.spec_from_file_location("covey_replay", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def c_str(s):
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append("".join("\\x%02x\" \"" % b for b in ch.encode("utf-8"))[:-3])
    return '"' + "".join(out) + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--replay", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    R = load_replay(a.replay)

    # ---- request vectors: (text, valid, t1, t2, max) ----
    reqs = []
    for t1, t2, mx in ((100, 200, 40), (0, 0, 1), (1755791000, 1755795000, 40),
                       (4294967295, 4294967295, 999)):
        txt = R.make_request(t1, t2, mx)
        assert R.parse_request(txt) == (t1, t2, mx), txt
        reqs.append((txt, True, t1, t2, mx))
    # parity edges: python str.split() semantics the C side must match
    for txt in ("RPL?  100  200  40", "RPL? 100\t200 40", "RPL? 100 200 40 "):
        assert R.parse_request(txt) == (100, 200, 40), txt
        reqs.append((txt, True, 100, 200, 40))
    for txt in ("RPL? 200 100 40",        # inverted window
                "RPL? 100 200 0",         # zero max
                "RPL? +5 200 40",         # int() leniency, refused both sides
                "RPL? -5 200 40",
                "RPL? 100 200",           # arity
                "RPL? 100 200 40 7",      # a fourth field is malformed, not v2
                "RPL? 4294967296 4294967297 1",   # beyond uint32, refused both sides
                "RPL? a b c",
                "RPL 100 aabbccdd ch x",  # a record is not a request
                "RPL?100 200 40"):        # no space after the prefix
        assert R.parse_request(txt) is None, txt
        reqs.append((txt, False, 0, 0, 0))

    # ---- record-format vectors: (ts, sender, chan, text) -> exact line ----
    recs = []
    for ts, sender, chan, text in (
            (1755791640, 0x62B8D2FD, "Howe group", "Testing hello"),
            (5, 0x1EC2BCA2, "a%b c", "x % y ~ z"),
            (7, 0xAABBCCDD, "ch", "line\nbreak\rgone"),
            (0, 0x00000001, "LongFast", "clockless zero is a legal ts"),
            (1700000000, 0x43588D68, "booksync", "deer spotted \U0001F98C at 40yd"),
            (1700000001, 0xFFFFFFFF, "x", "")):
        line = R.make_record_line(ts, sender, chan, text)
        assert line is not None
        p = R.parse_record_line(line)
        assert p is not None and p["chan"] == chan, line
        recs.append((ts, sender, chan, text, line))

    # ---- summary vectors ----
    sums = []
    for sent, gap in ((0, False), (12, True), (40, False)):
        txt = R.make_summary(sent, gap)
        assert R.parse_summary(txt) == (sent, gap), txt
        sums.append((sent, gap, txt))

    # ---- machine-traffic classification ----
    is_replay = ["RPL? 1 2 3", "RPL 1 aabbccdd ch x", "RPL. 1 0", "RPL", "RPL2 future"]
    not_replay = ["really? cool", "CBS1 abc def", "rpl lowercase is chat", " RPL leading space"]
    for t in is_replay:
        assert R.is_replay_text(t), t
    for t in not_replay:
        assert not R.is_replay_text(t), t

    with open(a.out, "w") as f:
        w = lambda s="": f.write(s + "\n")
        w("/* GENERATED by tools/gen_replay_vectors.py — DO NOT EDIT.")
        w(" *")
        w(" * Frozen behavior of COVEY's covey_ui/replay.py (the reference")
        w(" * implementation of docs/replay-spec.md). test_replay.cpp proves")
        w(" * replay_proto.cpp agrees byte-for-byte; a failure here means the")
        w(" * two devices would disagree on the wire.")
        w(" * PACKET_BUDGET=%d" % R.PACKET_BUDGET)
        w(" */")
        w("#ifndef VECTORS_REPLAY_H")
        w("#define VECTORS_REPLAY_H")
        w()
        w("typedef struct { const char* text; int valid; unsigned t1, t2; int maxn; } RplReqVec;")
        w("static const RplReqVec RPL_REQ_VEC[] = {")
        for txt, ok, t1, t2, mx in reqs:
            w("  { %s, %d, %uu, %uu, %d }," % (c_str(txt), 1 if ok else 0, t1, t2, mx))
        w("};")
        w("static const int RPL_REQ_VEC_N = %d;" % len(reqs))
        w()
        w("typedef struct { unsigned ts, sender; const char* chan; const char* text; const char* line; } RplRecVec;")
        w("static const RplRecVec RPL_REC_VEC[] = {")
        for ts, sender, chan, text, line in recs:
            w("  { %uu, 0x%08Xu, %s, %s, %s }," % (ts, sender, c_str(chan), c_str(text), c_str(line)))
        w("};")
        w("static const int RPL_REC_VEC_N = %d;" % len(recs))
        w()
        w("typedef struct { int sent, gap; const char* text; } RplSumVec;")
        w("static const RplSumVec RPL_SUM_VEC[] = {")
        for sent, gap, txt in sums:
            w("  { %d, %d, %s }," % (sent, 1 if gap else 0, c_str(txt)))
        w("};")
        w("static const int RPL_SUM_VEC_N = %d;" % len(sums))
        w()
        w("static const char* const RPL_IS_REPLAY[] = {")
        for t in is_replay:
            w("  %s," % c_str(t))
        w("};")
        w("static const int RPL_IS_REPLAY_N = %d;" % len(is_replay))
        w("static const char* const RPL_NOT_REPLAY[] = {")
        for t in not_replay:
            w("  %s," % c_str(t))
        w("};")
        w("static const int RPL_NOT_REPLAY_N = %d;" % len(not_replay))
        w()
        w("#endif // VECTORS_REPLAY_H")
    print("wrote %s: %d req, %d rec, %d sum vectors" % (a.out, len(reqs), len(recs), len(sums)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
