#!/usr/bin/env python3
"""Generate tests/vectors_pki.h — interop vectors for mesh_pki.cpp.

Python's `cryptography` package plays the STOCK MESHTASTIC side (X25519 +
AES-256-CCM with an 8-byte tag are exactly what firmware 2.5+ uses for PKC
DMs, verified against src/mesh/CryptoEngine.cpp on 2026-08-19). A passing
test_pki therefore proves the phone's bytes against an independent
implementation of the same scheme, not against itself.

Needs: pip install cryptography    (any venv is fine; the output header is
what's committed, this script only regenerates it)

  python3 tools/gen_pki_vectors.py --out tests/vectors_pki.h
"""

import argparse
import hashlib

from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey
from cryptography.hazmat.primitives.ciphers.aead import AESCCM
from cryptography.hazmat.primitives import serialization


def clamp(raw: bytes) -> bytes:
    b = bytearray(raw)
    b[0] &= 248
    b[31] &= 127
    b[31] |= 64
    return bytes(b)


def x25519_pub(priv: bytes) -> bytes:
    key = X25519PrivateKey.from_private_bytes(priv)
    return key.public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw)


def x25519_shared(priv: bytes, peer_pub: bytes) -> bytes:
    from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PublicKey
    return X25519PrivateKey.from_private_bytes(priv).exchange(
        X25519PublicKey.from_public_bytes(peer_pub))


def pki_nonce(from_node: int, packet_id: int, extra_nonce: int) -> bytes:
    # Byte-equal to CryptoEngine::initNonce(): packetId as u64 LE with its high
    # half overwritten by extraNonce, then fromNode, then a zero byte. 13 bytes.
    return (packet_id.to_bytes(4, "little") + extra_nonce.to_bytes(4, "little")
            + from_node.to_bytes(4, "little") + b"\x00")


def pki_frame(key: bytes, from_node: int, packet_id: int, extra_nonce: int,
              plain: bytes) -> bytes:
    ct = AESCCM(key, tag_length=8).encrypt(
        pki_nonce(from_node, packet_id, extra_nonce), plain, None)
    return ct + extra_nonce.to_bytes(4, "little")   # ct already ends with tag(8)


def carr(name: str, data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 12):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 12]) + ",")
    body = "\n".join(lines)
    return f"static const uint8_t {name}[{len(data)}] = {{\n{body}\n}};\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    out = []
    out.append("// GENERATED by tools/gen_pki_vectors.py — do not edit by hand.\n"
               "// Python `cryptography` (X25519 + AES-256-CCM tag=8) playing the\n"
               "// stock-Meshtastic side of the PKC DM scheme.\n"
               "#ifndef VECTORS_PKI_H\n#define VECTORS_PKI_H\n"
               "#include <stdint.h>\n#include <stddef.h>\n")

    # Deterministic keypairs. Arbitrary but fixed bytes, clamped like storage.
    phone_priv = clamp(hashlib.sha256(b"wiphone pki test private").digest())
    rak_priv = clamp(hashlib.sha256(b"rak pki test private").digest())
    phone_pub = x25519_pub(phone_priv)
    rak_pub = x25519_pub(rak_priv)
    shared_ab = x25519_shared(phone_priv, rak_pub)
    shared_ba = x25519_shared(rak_priv, phone_pub)
    assert shared_ab == shared_ba
    session_key = hashlib.sha256(shared_ab).digest()   # CryptoEngine::hash()

    out.append(carr("PKI_PHONE_PRIV", phone_priv))
    out.append(carr("PKI_PHONE_PUB", phone_pub))
    out.append(carr("PKI_RAK_PRIV", rak_priv))
    out.append(carr("PKI_RAK_PUB", rak_pub))
    out.append(carr("PKI_SESSION_KEY", session_key))

    # RFC 7748 section 5.2 vector 1: proves the vendored donna against the RFC,
    # not just against python.
    rfc_scalar = bytes.fromhex(
        "a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4")
    rfc_u = bytes.fromhex(
        "e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c")
    rfc_expect = bytes.fromhex(
        "c3da55379de9c6908e94ea4df28d084f32eccf03491c71f754b4075577a28552")
    out.append(carr("PKI_RFC7748_SCALAR", rfc_scalar))
    out.append(carr("PKI_RFC7748_U", rfc_u))
    out.append(carr("PKI_RFC7748_EXPECT", rfc_expect))

    # Frame vectors. Node numbers shaped like the real fleet's; lengths cover
    # sub-block, block-aligned, and the DM maximum (233 on-air minus overhead).
    phone_node = 0x08D63234
    rak_node = 0x33646708

    # A realistic Data protobuf for "hi": portnum=1, payload="hi", bitfield=0.
    data_hi = bytes([0x08, 0x01, 0x12, 0x02]) + b"hi" + bytes([0x48, 0x00])

    cases = [
        ("RAK2PHONE_HI", rak_node, phone_node, 0x1A2B3C4D, 0x51F0E1D2, data_hi),
        ("RAK2PHONE_BLK", rak_node, phone_node, 0x00000001, 0x00000000,
         bytes(range(32))),                       # extraNonce 0: high id half stays 0
        ("PHONE2RAK_TXT", phone_node, rak_node, 0xDEADBEEF, 0xC0FFEE01,
         bytes([0x08, 0x01, 0x12, 0x1A]) + b"meet at the north treeline"
         + bytes([0x48, 0x00])),
        ("PHONE2RAK_MAX", phone_node, rak_node, 0x7FFFFFFF, 0xA5A5A5A5,
         bytes((i * 7 + 3) & 0xFF for i in range(233 - 12))),
    ]
    names = []
    for name, frm, to, pkt_id, extra, plain in cases:
        frame = pki_frame(session_key, frm, pkt_id, extra, plain)
        out.append(carr(f"PKI_{name}_PLAIN", plain))
        out.append(carr(f"PKI_{name}_FRAME", frame))
        out.append(f"#define PKI_{name}_FROM 0x{frm:08x}u\n"
                   f"#define PKI_{name}_TO 0x{to:08x}u\n"
                   f"#define PKI_{name}_ID 0x{pkt_id:08x}u\n"
                   f"#define PKI_{name}_EXTRA 0x{extra:08x}u\n")
        names.append(name)

    out.append("#endif // VECTORS_PKI_H\n")
    with open(args.out, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {args.out}: {len(cases)} frame vectors, session key "
          f"{session_key[:4].hex()}…")


if __name__ == "__main__":
    main()
