#!/usr/bin/env python3
"""Generate SMS-mirror interop vectors by running COVEY'S OWN smsmirror.py.

The point is the same as tools/gen_booksync_vectors.py: the phone's parser must agree with
COVEY's encoder BYTE FOR BYTE, and the only way to prove that is to run COVEY's actual code
rather than a second reading of the spec. A disagreement here is silent on both devices —
a mirrored text simply never appears, or appears twice — so it must be caught on the Mac.

    python3 tools/gen_smsmirror_vectors.py \
        --smsmirror ../New_phone_project/Project_definition_and_documents/\
COVEY_RevA_v0.5/firmware/pi/covey-ui/covey_ui/smsmirror.py \
        --out tests/vectors_smsmirror.h

Then ./tests/run_tests.sh, which parses every line below with WiPhone/sms_mirror.cpp.
"""
import argparse
import importlib.util
import os
import sys


def load(path):
    spec = importlib.util.spec_from_file_location("covey_smsmirror", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# label, id, peer-as-COVEY-would-hold-it, out, ts, text
CASES = [
    ("plain_in",      884451201, "4257604281", False, 0x68A1B2C3, "on my way, be there in ten"),
    ("plain_out",     884451202, "4257604281", True,  0x68A1B2D0, "ok see you then"),
    ("spaces",        884451203, "4257604281", True,  0x68A1B2D1, "sure  -  see you at 5 (bring the  map)"),
    ("leading_space", 884451204, "4257604281", True,  0x68A1B2D2, " leading space matters"),
    ("empty_text",    884451205, "4257604281", False, 0x68A1B2D3, ""),
    ("looks_nested",  884451206, "4257604281", False, 0x68A1B2D4, "CSM1 99 5551234567 o 1 gotcha"),
    ("multiline",     884451207, "4257604281", False, 0x68A1B2D5, "line one\nline two\r\nline three"),
    ("backslash",     884451208, "4257604281", True,  0x68A1B2D6, "C:\\path\\n not a newline"),
    ("unicode",       884451209, "4257604281", False, 0x68A1B2D7, "cafe\u0301 \u2014 na\u00efve resume\u0301"),
    ("max_len",       2147483647, "4257604281", False, 0xFFFFFFFF, "W" * 160),
    # The number as it is spelled elsewhere: COVEY normalises before it reaches the wire, so
    # all three of these must come out identical to plain_out's peer field.
    ("peer_e164",     884451210, "+14257604281", True, 0x68A1B2D8, "typed with a country code"),
    ("peer_pretty",   884451211, "(425) 760-4281", True, 0x68A1B2D9, "typed by a human"),
    ("peer_sipuri",   884451212, "sip:+14257604281@seattle1.voip.ms", False, 0x68A1B2DA, "off the wire"),
]


def cstr(s):
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif " " <= ch <= "~":
            out.append(ch)
        else:
            for b in ch.encode("utf-8"):        # the wire is bytes; keep it byte-exact
                out.append("\\x%02x" % b)
    return '"' + "".join(out) + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--smsmirror", required=True, help="path to COVEY's covey_ui/smsmirror.py")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    m = load(args.smsmirror)
    rows = []
    for label, mid, peer, out, ts, text in CASES:
        line = m.pack({"id": mid, "peer": peer, "out": out, "ts": ts, "text": text})
        if line is None:
            print("refused to pack: %s" % label, file=sys.stderr)
            return 1
        if len(line) > m.MESH_MAX:
            print("WARNING: %s is %d bytes, over the %d-byte on-air budget"
                  % (label, len(line), m.MESH_MAX), file=sys.stderr)
        # Prove COVEY can read its own output before asking the phone to.
        back = m.parse(line)
        assert back and back["text"] == text and back["id"] == mid, label
        rows.append((label, line, mid, m.digits(peer), out, ts, text))

    with open(args.out, "w") as f:
        f.write("/* GENERATED by tools/gen_smsmirror_vectors.py — do not edit.\n"
                " *\n"
                " * Produced by running COVEY's own covey_ui/smsmirror.py, so these are the\n"
                " * bytes the radio and the LAN socket will actually carry. Regenerate after\n"
                " * ANY change to the format on either side.\n"
                " *\n"
                " * source: %s\n"
                " */\n" % os.path.basename(args.smsmirror))
        f.write("#ifndef VECTORS_SMSMIRROR_H\n#define VECTORS_SMSMIRROR_H\n\n")
        f.write("struct SmVec {\n"
                "  const char* label;\n"
                "  const char* line;      // exactly what COVEY puts on the wire\n"
                "  long long   id;\n"
                "  const char* peer;      // normalised digits\n"
                "  bool        out;\n"
                "  unsigned long ts;\n"
                "  const char* text;      // what the phone must recover\n"
                "};\n\n")
        f.write("static const SmVec SM_VECS[] = {\n")
        for label, line, mid, peer, out, ts, text in rows:
            f.write("  { %s, %s, %dLL, %s, %s, %luUL, %s },\n"
                    % (cstr(label), cstr(line), mid, cstr(peer),
                       "true" if out else "false", ts, cstr(text)))
        f.write("};\n")
        f.write("static const int SM_VEC_N = %d;\n\n" % len(rows))
        f.write("#endif // VECTORS_SMSMIRROR_H\n")
    print("wrote %s (%d vectors)" % (args.out, len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
