#!/usr/bin/env python3
"""Generate tests/vectors_neighbor.h from the REAL Meshtastic protobufs.

The phone hand-rolls its NeighborInfo encoding (no nanopb in this firmware), so
the only honest check is against the actual protobuf runtime every other node in
the mesh uses. This emits the exact bytes python produces for a set of cases;
tests/test_neighbor.cpp asserts the firmware produces them byte for byte.

    python3 tools/gen_neighbor_vectors.py --out tests/vectors_neighbor.h
"""
import argparse
import sys

from meshtastic.protobuf import mesh_pb2, portnums_pb2


CASES = [
    # (label, my_node, interval, [(node, snr), ...])
    ("empty", 0x62B8D2FD, 3600, []),
    ("one", 0x62B8D2FD, 3600, [(0x1EC2BCA2, 6.25)]),
    ("two", 0x62B8D2FD, 14400, [(0x1EC2BCA2, 6.25), (0x43588D68, -12.75)]),
    ("small_ids", 0x00000001, 60, [(0x0000007F, 0.0), (0x00000080, 1.0)]),
    ("max_id", 0xFFFFFFFF, 4294967295, [(0xFFFFFFFF, -0.25)]),
    ("negzero_snr", 0x11223344, 900, [(0x55667788, -0.0)]),
]


def c_bytes(b):
    return ", ".join("0x%02x" % x for x in b)


def c_float(v):
    """A C float literal that is always valid: %g alone yields '0' -> '0f',
    which the compiler reads as an octal constant with a stray 'f'."""
    s = "%.10g" % v
    if "." not in s and "e" not in s and "E" not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s + "f"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    rows = []
    for label, mynode, interval, neighbors in CASES:
        m = mesh_pb2.NeighborInfo()
        m.node_id = mynode
        m.last_sent_by_id = mynode
        m.node_broadcast_interval_secs = interval
        for nid, snr in neighbors:
            n = m.neighbors.add()
            n.node_id = nid
            n.snr = snr
        raw = m.SerializeToString()
        # Round-trip guard: a vector that does not survive the real parser
        # would pin the firmware to a format nothing else can read.
        back = mesh_pb2.NeighborInfo()
        back.ParseFromString(raw)
        assert back.node_id == mynode and len(back.neighbors) == len(neighbors), label
        for (nid, snr), got in zip(neighbors, back.neighbors):
            assert got.node_id == nid and abs(got.snr - snr) < 1e-6, label
        rows.append((label, mynode, interval, neighbors, raw))

    with open(a.out, "w") as f:
        w = lambda s="": f.write(s + "\n")
        w("/* GENERATED by tools/gen_neighbor_vectors.py — DO NOT EDIT.")
        w(" *")
        w(" * Bytes produced by the REAL Meshtastic protobuf runtime for")
        w(" * NeighborInfo (portnum %d). test_neighbor.cpp proves this"
          % portnums_pb2.PortNum.Value("NEIGHBORINFO_APP"))
        w(" * firmware's hand-rolled encoder agrees byte for byte — if it")
        w(" * does not, other radios cannot read our neighbour list.")
        w(" */")
        w("#ifndef VECTORS_NEIGHBOR_H")
        w("#define VECTORS_NEIGHBOR_H")
        w()
        w("typedef struct { unsigned node; float snr; } NbrVecEntry;")
        w("typedef struct {")
        w("  const char* label; unsigned myNode; unsigned interval;")
        w("  const NbrVecEntry* entries; int count;")
        w("  const unsigned char* bytes; int len;")
        w("} NbrVec;")
        w()
        for i, (label, mynode, interval, neighbors, raw) in enumerate(rows):
            if neighbors:
                w("static const NbrVecEntry NBR_E%d[] = { %s };"
                  % (i, ", ".join("{ 0x%08Xu, %s }" % (n, c_float(s)) for n, s in neighbors)))
            else:
                w("static const NbrVecEntry NBR_E%d[1] = { { 0u, 0.0f } };" % i)
            w("static const unsigned char NBR_B%d[] = { %s };" % (i, c_bytes(raw)))
        w()
        w("static const NbrVec NBR_VEC[] = {")
        for i, (label, mynode, interval, neighbors, raw) in enumerate(rows):
            w('  { "%s", 0x%08Xu, %uu, NBR_E%d, %d, NBR_B%d, %d },'
              % (label, mynode, interval, i, len(neighbors), i, len(raw)))
        w("};")
        w("static const int NBR_VEC_N = %d;" % len(rows))
        w()
        w("#endif // VECTORS_NEIGHBOR_H")
    print("wrote %s: %d vectors" % (a.out, len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
