#!/usr/bin/env python3
"""Generate tests/vectors_pos.h — interop vectors for WiPhone/mesh_pos.cpp.

Position (portnum 3) and Waypoint (portnum 8) are hand-rolled in mesh_pos.cpp, and until
2026-09-02 tests/test_pos.cpp checked them only against bytes written BY HAND in the same
file — a test of the author's understanding, not of the protocol. This emits what the real
Meshtastic python runtime produces, so a passing test_pos proves the phone reads exactly
what COVEY's RAK puts on the air every five minutes, and that what the phone's own beacon
sends is what a stock node will parse.

Covers:
  * Position ENCODE — meshPosBuild(lat, lon, time) must equal python byte for byte
  * Position DECODE — python-built Positions, including a STOCK-SHAPED one carrying the
    high-numbered fields real firmware appends (sats_in_view=19, precision_bits=23, with
    two-byte tags), altitude, DOPs, ground speed and the presence-tracked fields
  * Waypoint DECODE — full, deletion marker (id only), long name, unknown fields 7/8
  * Negative: a Position missing longitude must be refused

    python3 tools/gen_pos_vectors.py --out tests/vectors_pos.h
"""

import argparse
import sys

try:
    from meshtastic.protobuf import mesh_pb2
    from importlib.metadata import version as _pkgver
except ImportError:
    sys.exit("need the meshtastic package: pip install meshtastic")

SEA_LAT, SEA_LON = 476062000, -1223321000     # 47.6062, -122.3321
PDX_LAT, PDX_LON = 455152000, -1226784000     # 45.5152, -122.6784
CAMP_LAT, CAMP_LON = 474432800, -1222946200   # the woods, roughly


def c_bytes(b: bytes) -> str:
    return ", ".join(f"0x{x:02x}" for x in b) if b else "0"


def c_str(t: str) -> str:
    out, prev = "", False
    for b in t.encode("utf-8"):
        ch = chr(b)
        if b > 0x7e or b < 0x20 or ch in '"\\':
            out += f"\\x{b:02x}"; prev = True
        else:
            if prev and ch in "0123456789abcdefABCDEF":
                out += '""'
            out += ch; prev = False
    return out


def emit(out):
    ver = _pkgver("meshtastic")
    w = out.write
    w("/*\n * vectors_pos.h — GENERATED by tools/gen_pos_vectors.py. Do not hand-edit.\n")
    w(f" * Produced by the real Meshtastic protobuf runtime, package version {ver}.\n")
    w(" * tests/test_pos.cpp asserts WiPhone/mesh_pos.cpp produces and parses exactly these.\n */\n\n")
    w("#ifndef VECTORS_POS_H\n#define VECTORS_POS_H\n\n")
    w(f'#define POS_VEC_MESHTASTIC_VERSION "{ver}"\n\n')

    # ---- Position encode: what meshPosBuild must produce ------------------------------
    # (label, lat, lon, time). time==0 means "omit" in the firmware; python omits a
    # default fixed32 too, so the shapes agree — that agreement is part of what is tested.
    enc = [
        ("pos_seattle_timed",   SEA_LAT,  SEA_LON,  1766000000),
        ("pos_seattle_untimed", SEA_LAT,  SEA_LON,  0),
        ("pos_south_west",      PDX_LAT,  PDX_LON,  1),
        ("pos_negative_lat",   -338688200, 1512092900, 1766000000),   # Sydney: both signs
        ("pos_zero_zero",       0,        0,        1766000000),      # presence-tracked: 0 is SENT
        ("pos_time_max",        SEA_LAT,  SEA_LON,  0xFFFFFFFF),
    ]
    w("typedef struct {\n  const char* label;\n  long latI;\n  long lonI;\n  unsigned long time;\n"
      "  const unsigned char* bytes;\n  int len;\n} PosEncVec;\n\n")
    for i, (label, lat, lon, t) in enumerate(enc):
        p = mesh_pb2.Position(); p.latitude_i = lat; p.longitude_i = lon
        if t:
            p.time = t
        b = p.SerializeToString()
        w(f"static const unsigned char POS_ENC_B_{i}[] = {{ {c_bytes(b)} }};\n")
    w("\nstatic const PosEncVec POS_ENC[] = {\n")
    for i, (label, lat, lon, t) in enumerate(enc):
        p = mesh_pb2.Position(); p.latitude_i = lat; p.longitude_i = lon
        if t:
            p.time = t
        b = p.SerializeToString()
        w(f'  {{ "{label}", {lat}L, {lon}L, {t}UL, POS_ENC_B_{i}, {len(b)} }},\n')
    w("};\n")
    w(f"#define POS_ENC_N {len(enc)}\n\n")

    # ---- Position decode: what meshPosParse must read ---------------------------------
    dec = []
    p = mesh_pb2.Position(); p.latitude_i = SEA_LAT; p.longitude_i = SEA_LON; p.time = 1766000000
    dec.append(("pdec_plain", p.SerializeToString(), 1, SEA_LAT, SEA_LON, 1766000000))
    # A STOCK-FIRMWARE-SHAPED broadcast: every field a RAK actually sends, including the
    # two-byte-tag ones (>= 16). This is the packet COVEY puts on the air every 5 minutes.
    p = mesh_pb2.Position()
    p.latitude_i = CAMP_LAT; p.longitude_i = CAMP_LON; p.altitude = 412
    p.time = 1766000123; p.location_source = 2; p.altitude_source = 1
    p.timestamp = 1766000120; p.timestamp_millis_adjust = -250
    p.altitude_hae = 430; p.altitude_geoidal_separation = -18
    p.PDOP = 180; p.HDOP = 120; p.VDOP = 140; p.gps_accuracy = 3500
    p.ground_speed = 0; p.ground_track = 27000; p.fix_quality = 1; p.fix_type = 3
    p.sats_in_view = 9; p.sensor_id = 0; p.next_update = 300; p.seq_number = 41
    p.precision_bits = 32
    dec.append(("pdec_stock_full", p.SerializeToString(), 1, CAMP_LAT, CAMP_LON, 1766000123))
    # ⚠ NEGATIVE int32 = TEN-BYTE VARINT. altitude is int32 (not sint32), so a fix below sea
    # level is sign-extended to 64 bits on the wire: 0xce 0xff 0xff 0xff 0xff 0xff 0xff 0xff
    # 0xff 0x01. The reader must step over all ten bytes AND not shift a uint32 by 63 doing
    # it (UBSan caught exactly that on 2026-09-02). Death Valley is a real place.
    p = mesh_pb2.Position(); p.latitude_i = 362431000; p.longitude_i = -1168163000
    p.altitude = -86; p.time = 1766000200; p.sats_in_view = 11
    dec.append(("pdec_below_sea_level", p.SerializeToString(), 1, 362431000, -1168163000, 1766000200))
    # sfixed32 sign handling on the negative side of both axes
    p = mesh_pb2.Position(); p.latitude_i = -338688200; p.longitude_i = -1510000000
    dec.append(("pdec_both_negative", p.SerializeToString(), 1, -338688200, -1510000000, 0))
    # presence-tracked zero: a Position AT 0,0 is a real fix and must parse
    p = mesh_pb2.Position(); p.latitude_i = 0; p.longitude_i = 0; p.time = 5
    dec.append(("pdec_null_island", p.SerializeToString(), 1, 0, 0, 5))
    # NEGATIVE: longitude absent -> must be refused (a fix-less position is useless here)
    p = mesh_pb2.Position(); p.latitude_i = SEA_LAT; p.time = 1766000000; p.sats_in_view = 4
    dec.append(("pdec_no_longitude", p.SerializeToString(), 0, 0, 0, 0))
    # NEGATIVE: nothing but telemetry
    p = mesh_pb2.Position(); p.sats_in_view = 0; p.precision_bits = 32; p.time = 7
    dec.append(("pdec_no_fix_at_all", p.SerializeToString(), 0, 0, 0, 0))
    w("typedef struct {\n  const char* label;\n  const unsigned char* bytes;\n  int len;\n"
      "  int expectOk;\n  long latI;\n  long lonI;\n  unsigned long time;\n} PosDecVec;\n\n")
    for i, (label, b, ok, lat, lon, t) in enumerate(dec):
        w(f"static const unsigned char POS_DEC_B_{i}[] = {{ {c_bytes(b)} }};\n")
    w("\nstatic const PosDecVec POS_DEC[] = {\n")
    for i, (label, b, ok, lat, lon, t) in enumerate(dec):
        w(f'  {{ "{label}", POS_DEC_B_{i}, {len(b)}, {ok}, {lat}L, {lon}L, {t}UL }},\n')
    w("};\n")
    w(f"#define POS_DEC_N {len(dec)}\n\n")

    # ---- Waypoint decode ------------------------------------------------------------------
    wps = []
    q = mesh_pb2.Waypoint(); q.id = 42; q.latitude_i = CAMP_LAT; q.longitude_i = CAMP_LON
    q.expire = 1766100000; q.locked_to = 0x62B8D2FD; q.name = "Camp"
    wps.append(("wp_camp", q.SerializeToString(), 1, 42, 1, CAMP_LAT, CAMP_LON, 1766100000, 0x62B8D2FD, "Camp"))
    # DELETION MARKER: id and nothing else. Meshtastic's convention — absence of position is
    # the discriminator (expire==0 means "never", so it cannot be). Must parse with hasPos=0.
    q = mesh_pb2.Waypoint(); q.id = 42
    wps.append(("wp_delete_marker", q.SerializeToString(), 1, 42, 0, 0, 0, 0, 0, ""))
    # Fields the phone does not read (description=7, icon=8) around the ones it does.
    q = mesh_pb2.Waypoint(); q.id = 7; q.latitude_i = SEA_LAT; q.longitude_i = SEA_LON
    q.name = "Truck"; q.description = "parked by the gate, keys under the mat"; q.icon = 0x1F69A
    wps.append(("wp_unknown_fields", q.SerializeToString(), 1, 7, 1, SEA_LAT, SEA_LON, 0, 0, "Truck"))
    # A name longer than MESH_WP_NAME_LEN-1 (19) must be truncated, not overrun.
    q = mesh_pb2.Waypoint(); q.id = 9; q.latitude_i = 1; q.longitude_i = 2
    q.name = "A very long stand name indeed"
    wps.append(("wp_long_name", q.SerializeToString(), 1, 9, 1, 1, 2, 0, 0, "A very long stand n"))
    # UTF-8 in a name (bounded copy must not split... well, it may — but must terminate).
    q = mesh_pb2.Waypoint(); q.id = 11; q.latitude_i = 3; q.longitude_i = 4; q.name = "Café"
    wps.append(("wp_utf8_name", q.SerializeToString(), 1, 11, 1, 3, 4, 0, 0, "Café"))
    # NEGATIVE: no id -> refused
    q = mesh_pb2.Waypoint(); q.latitude_i = SEA_LAT; q.longitude_i = SEA_LON; q.name = "Nameless"
    wps.append(("wp_no_id", q.SerializeToString(), 0, 0, 0, 0, 0, 0, 0, ""))
    w("typedef struct {\n  const char* label;\n  const unsigned char* bytes;\n  int len;\n"
      "  int expectOk;\n  unsigned long id;\n  int hasPos;\n  long latI;\n  long lonI;\n"
      "  unsigned long expire;\n  unsigned long lockedTo;\n  const char* name;\n} WpDecVec;\n\n")
    for i, row in enumerate(wps):
        w(f"static const unsigned char WP_DEC_B_{i}[] = {{ {c_bytes(row[1])} }};\n")
    w("\nstatic const WpDecVec WP_DEC[] = {\n")
    for i, (label, b, ok, wid, hp, lat, lon, exp, lock, name) in enumerate(wps):
        w(f'  {{ "{label}", WP_DEC_B_{i}, {len(b)}, {ok}, {wid}UL, {hp}, {lat}L, {lon}L, '
          f'{exp}UL, {lock}UL, "{c_str(name)}" }},\n')
    w("};\n")
    w(f"#define WP_DEC_N {len(wps)}\n\n")
    w("#endif // VECTORS_POS_H\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    with open(a.out, "w") as f:
        emit(f)
    print(f"wrote {a.out} (meshtastic {_pkgver('meshtastic')})")


if __name__ == "__main__":
    main()
