#!/usr/bin/env python3
"""Generate C test vectors for booksync.cpp from COVEY's OWN booksync.py.

The WiPhone's C++ implementation has to produce byte-identical output to COVEY's Python,
or a sync packet is silently dropped (a wrong passcode and a wrong implementation look
exactly the same on the wire — that is deliberate, see D-089). So the vectors are not
hand-written from reading the spec: they are generated by importing and RUNNING the real
module, which makes them ground truth rather than a second opinion.

Usage:
    python3 tools/gen_booksync_vectors.py \
        --booksync /path/to/covey-ui/covey_ui/booksync.py \
        --out tests/vectors_booksync.h

Re-run this if COVEY's booksync.py ever changes; the C tests will then fail loudly
rather than drift silently apart.
"""
import argparse
import importlib.util
import os
import sys


def load_booksync(path):
    spec = importlib.util.spec_from_file_location("covey_booksync", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def c_str(s):
    """A C string literal for `s`, escaping non-ASCII as hex bytes so the file stays ASCII."""
    out = []
    for b in s.encode("utf-8"):
        ch = chr(b)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif 0x20 <= b < 0x7F:
            out.append(ch)
        else:
            # \xNN can swallow a following hex digit; split the literal to stop that.
            out.append('\\x%02x""' % b)
    return '"' + "".join(out) + '"'


# (label, passcode) — the key derivation is the root of everything else.
# ⚠ These are INVENTED values that exist only to pin the algorithm. Do not put a real
# booksync passcode in here: this repository is PUBLIC, and the vectors below embed both the
# passcode and its derived key, which is the whole secret. The tests prove interop equally
# well with made-up ones.
KEYS = [
    ("empty",    ""),
    ("vec-a",    "vector-passcode-a"),
    ("vec-b",    "vector-passcode-b"),
    ("digits",   "0000"),
    ("longpw",   "a much longer passphrase with spaces 12345"),
]
VEC_PW = "vector-passcode-a"        # the passcode every record vector is signed with

# (label, ids, spine, offset, fraction, turned_at, device, nonce)
RECORDS = [
    ("plain",
     ["id:pg-1342", "ta:pride-and-prejudice-jane-austen", "fp:0123456789abcdef"],
     7, 4213, 0.3125, 1754870400, "COVEY", "deadbeef"),
    ("start",
     ["ta:moby-dick-herman-melville", "fp:aabbccdd00112233"],
     0, 0, 0.0, 1700000000, "WiPhone", "00000000"),
    ("end",
     ["id:urn-uuid-9f8e7d6c", "fp:ffeeddccbbaa9988"],
     412, 4294967295, 1.0, 4294967295, "T-Deck", "ffffffff"),
    ("txt-book",
     ["ta:my-notes", "fp:1122334455667788"],
     0, 987, 0.5, 1754870401, "COVEY", "0a1b2c3d"),
    # Quantisation stress: fractions that do not land on a 1/65535th boundary, which is
    # where a %.6f formatting difference between Python and C would show up first.
    ("frac-third",
     ["id:x", "fp:0000000000000000"],
     3, 100, 1.0 / 3.0, 1754870402, "COVEY", "11223344"),
    ("frac-tiny",
     ["id:y", "fp:1111111111111111"],
     0, 1, 0.0000152590219, 1754870403, "COVEY", "55667788"),
    ("frac-near-one",
     ["id:z", "fp:2222222222222222"],
     99, 65535, 0.9999847412, 1754870404, "COVEY", "99aabbcc"),
    # Truncation edges. reduce_for_mesh cuts the first id to 40 BYTES and dev to 12 BYTES.
    ("long-id",
     ["ta:" + "a" * 64, "fp:3333333333333333"],
     1, 2, 0.25, 1754870405, "COVEY", "0badc0de"),
    ("long-dev",
     ["id:dev-trunc", "fp:4444444444444444"],
     1, 2, 0.75, 1754870406, "AVeryLongDeviceNm", "cafebabe"),
    # Multi-byte device name: the cut is on BYTES, then a partial character is dropped.
    # "é" is 2 bytes, so 7 of them is 14 bytes -> cut to 12 -> 6 characters survive.
    ("utf8-dev",
     ["id:utf8", "fp:5555555555555555"],
     5, 6, 0.5, 1754870407, "é" * 7, "feedface"),
    # Clamping: spine above 65535 and offset above 2^32-1 are clamped by reduce_for_mesh.
    ("clamp-spine",
     ["id:clamp", "fp:6666666666666666"],
     70000, 5, 0.125, 1754870408, "COVEY", "12345678"),
    # An out-of-range fraction is NOT clamped by make_record (only reduce_for_mesh clamps),
    # so the full canonical still prints it verbatim. Pins that asymmetry.
    ("frac-over-one",
     ["id:over", "fp:7777777777777777"],
     2, 3, 1.5, 1754870410, "COVEY", "aabbccdd"),
    ("frac-negative",
     ["id:under", "fp:8888888888888888"],
     2, 3, -0.25, 1754870411, "COVEY", "eeff0011"),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--booksync", required=True, help="path to COVEY's covey_ui/booksync.py")
    ap.add_argument("--out", required=True, help="header file to write")
    args = ap.parse_args()

    if not os.path.exists(args.booksync):
        sys.exit("no such file: %s" % args.booksync)
    bs = load_booksync(args.booksync)

    L = []
    w = L.append
    w("/* GENERATED by tools/gen_booksync_vectors.py from COVEY's booksync.py — do not edit.")
    w(" *")
    w(" * Ground truth for the WiPhone's C++ port. Every string here was produced by running")
    w(" * COVEY's real implementation, so a test failure means the two devices would have")
    w(" * silently failed to sync on air.")
    w(" *")
    w(" * booksync.py VERSION=%d  MAC_LEN=%d  KDF_SALT=%s  MESH_PREFIX=%s"
      % (bs.VERSION, bs.MAC_LEN, bs.KDF_SALT, bs.MESH_PREFIX))
    w(" */")
    w("#pragma once")
    w("")
    w("typedef struct { const char* label; const char* passcode; const char* keyHex; } BsKeyVec;")
    w("")
    w("typedef struct {")
    w("  const char* label;")
    w("  const char* ids[4];")
    w("  int         nIds;")
    w("  unsigned    spine;")
    w("  unsigned    offset;")
    w("  double      fraction;")
    w("  unsigned    turnedAt;")
    w("  const char* dev;")
    w("  const char* nonce;")
    w("  const char* passcode;")
    w("  const char* canonical;      /* _canonical(rec) of the FULL record */")
    w("  const char* mac;            /* sign(rec, key) of the FULL record  */")
    w("  const char* reducedCanon;   /* _canonical(reduce_for_mesh(rec))   */")
    w("  const char* reducedId;      /* the single id a mesh packet carries */")
    w("  const char* reducedDev;")
    w("  unsigned    reducedSpine;")
    w("  unsigned    reducedOffset;")
    w("  unsigned    reducedFrQ;     /* fraction quantised to 1/65535ths   */")
    w("  const char* meshText;       /* full 'CBS1 <payload> <mac>' packet */")
    w("} BsRecVec;")
    w("")

    w("static const BsKeyVec BS_KEY_VECS[] = {")
    for label, pw in KEYS:
        w('  { %s, %s, "%s" },' % (c_str(label), c_str(pw), bs.derive_key(pw).hex()))
    w("};")
    w("static const int BS_KEY_VEC_N = %d;" % len(KEYS))
    w("")

    w("static const BsRecVec BS_REC_VECS[] = {")
    for (label, ids, sp, off, fr, t, dev, nonce) in RECORDS:
        pw = VEC_PW
        key = bs.derive_key(pw)
        rec = bs.make_record(ids, sp, off, fr, t, device=dev, nonce=nonce)
        red = bs.reduce_for_mesh(rec)
        mesh = bs.pack_mesh(rec, key)
        frq = int(round(red["fr"] * 65535))
        idlist = ", ".join(c_str(i) for i in ids) + ", 0"
        w("  { %s," % c_str(label))
        w("    { %s }, %d," % (idlist, len(ids)))
        w("    %du, %du, %r, %du," % (sp, off, fr, t))
        w("    %s, %s, %s," % (c_str(dev), c_str(nonce), c_str(pw)))
        w("    %s," % c_str(bs._canonical(rec)))
        w("    %s," % c_str(bs.sign(rec, key)))
        w("    %s," % c_str(bs._canonical(red)))
        w("    %s, %s," % (c_str(red["ids"][0]), c_str(red["dev"])))
        w("    %du, %du, %du," % (red["sp"], red["off"], frq))
        w("    %s }," % c_str(mesh))
    w("};")
    w("static const int BS_REC_VEC_N = %d;" % len(RECORDS))
    w("")

    # Packets that must be REJECTED. Each is a real packet with exactly one thing wrong,
    # so a test failure names the specific check that stopped working.
    good_key = bs.derive_key(VEC_PW)
    good = bs.pack_mesh(bs.make_record(["id:reject-me", "fp:7777777777777777"],
                                       9, 10, 0.5, 1754870409, "COVEY", "a1b2c3d4"), good_key)
    payload, mac = good.split()[1], good.split()[2]

    def flip(s, i):
        """Change ONE base32 character at `i` to a genuinely different one.

        Naively substituting a fixed letter is not a tamper: the payload begins with the
        version byte 0x01, whose top five bits are 00000 = 'A', so 'A' + payload[1:] leaves
        the packet untouched and the "rejected" vector quietly verifies. The generator's
        own guard below caught exactly that.
        """
        ch = "B" if s[i] != "B" else "C"
        return s[:i] + ch + s[i + 1:]

    bad = [
        ("wrong-passcode",  good,                                   "vector-passcode-b"),
        ("tampered-mac",    "CBS1 %s %s" % (payload, flip(mac, len(mac) // 2)), VEC_PW),
        ("tampered-payload", "CBS1 %s %s" % (flip(payload, len(payload) // 2), mac), VEC_PW),
        ("truncated",       "CBS1 %s" % payload,                     VEC_PW),
        ("no-prefix",       "%s %s" % (payload, mac),                VEC_PW),
        ("wrong-prefix",    "CBS2 %s %s" % (payload, mac),           VEC_PW),
        ("empty",           "",                                      VEC_PW),
        ("prefix-only",     "CBS1 ",                                 VEC_PW),
        ("non-b32",         "CBS1 payload! %s" % mac,                VEC_PW),
        ("garbage",         "hello world this is a chat message",    VEC_PW),
    ]
    w("typedef struct { const char* label; const char* text; const char* passcode; } BsBadVec;")
    w("static const BsBadVec BS_BAD_VECS[] = {")
    for label, text, pw in bad:
        # Guard the generator itself: every one of these MUST fail to unpack.
        if bs.unpack_mesh(text, bs.derive_key(pw)) is not None:
            sys.exit("vector '%s' was supposed to be rejected but verified" % label)
        w("  { %s, %s, %s }," % (c_str(label), c_str(text), c_str(pw)))
    w("};")
    w("static const int BS_BAD_VEC_N = %d;" % len(bad))
    w("")

    # is_sync_text: chat-vs-machine classification, checked BEFORE the mac.
    sync_texts = [good, "CBS1 anything at all", "CBS1 "]
    chat_texts = ["CBS1", "hello", "", "cbs1 lower case", " CBS1 leading space", "CBS12 x y"]
    w("static const char* const BS_IS_SYNC[] = {")
    for t in sync_texts:
        assert bs.is_sync_text(t), t
        w("  %s," % c_str(t))
    w("};")
    w("static const int BS_IS_SYNC_N = %d;" % len(sync_texts))
    w("static const char* const BS_NOT_SYNC[] = {")
    for t in chat_texts:
        assert not bs.is_sync_text(t), t
        w("  %s," % c_str(t))
    w("};")
    w("static const int BS_NOT_SYNC_N = %d;" % len(chat_texts))
    w("")

    with open(args.out, "w") as f:
        f.write("\n".join(L) + "\n")
    print("wrote %s: %d key, %d record, %d reject, %d classify vectors"
          % (args.out, len(KEYS), len(RECORDS), len(bad), len(sync_texts) + len(chat_texts)))


if __name__ == "__main__":
    main()
