#!/usr/bin/env bash
# Publish a firmware update the phone can install over the air.
#
#   tools/publish_ota.sh 0.8.31
#
# Builds, stages the binary and manifest under ota/, and bumps FIRMWARE_VERSION so the
# phone actually offers it. Commit and push afterwards — the phone reads the manifest
# straight from the repo's main branch, so pushing IS releasing.
set -euo pipefail

ver="${1:-}"
if [ -z "$ver" ]; then
  echo "usage: $0 <version>   e.g. $0 0.8.31" >&2
  exit 1
fi

cd "$(dirname "$0")/.."
PIO="${PIO:-$HOME/Library/Python/3.9/bin/pio}"

# ⚠ The phone compares against FIRMWARE_VERSION compiled INTO the running build, and only
# offers an update when the manifest is higher. Bumping config.h and the manifest in one
# step is what stops them drifting -- a manifest that matches the installed version looks
# to the user exactly like a broken update check.
sed -i '' "s/#define FIRMWARE_VERSION .*/#define FIRMWARE_VERSION \"$ver\"/" WiPhone/config.h
echo "FIRMWARE_VERSION -> $ver"

"$PIO" run

mkdir -p ota
cp .pio/build/wiphone/firmware.bin ota/firmware.bin
cat > ota/wiphone-ota.ini <<INI
; Generated by tools/publish_ota.sh — do not hand-edit; see that script.
version = $ver
url = https://raw.githubusercontent.com/Nikguy321/wiphone-meshtastic/main/ota/firmware.bin
INI

echo
echo "staged ota/firmware.bin ($(wc -c < ota/firmware.bin) bytes) and ota/wiphone-ota.ini"
echo "now:  git add -A && git commit -m 'Release $ver' && git push"
echo "then: on the phone, Settings > Firmware settings > check for update"
